Info:     Reading OPTISTRUCT from C:/Users/sihol/OneDrive/Desktop/ASE/MATLAB/RESULT FILES/ASE_Project2025_SuperPanel_3787415_redesign.fem using C:\Program Files\Altair\2023.1\hwdesktop\io\model_readers\feinput\bin\win64\optistruct.exe on 07-02-2025 23:37:34.
Info:     Processing Modules.
Info:     Processing Cards.
Info:     Processing System Collectors.
Info:     Processing Systems.
Info:     Processing Nodes.
Info:     Processing Vectorcols.
Info:     Processing Vectors.
Info:     Processing Materials.
Info:     Processing Properties.
Info:     Processing Components.
Info:     Processing Groups.
Info:     Processing Elements.
Info:     Processing Load Collectors.
Info:     Processing Equations.
Info:     Processing Loads.
Info:     Processing Assemblies.
Info:     Processing Curves.
Info:     Processing Blocks.
Info:     Processing Sets.
Info:     Processing Output Blocks.
Info:     Processing Load Steps.
Info:     Processing Sensors.
Info:     Processing Plys.
Info:     Processing Laminates.
Info:     Processing Designvars.
Info:     Processing Beamsectcols.
Info:     Processing Beamsections.
Info:     Processing Optitableentrs.
Info:     Processing Dequations.
Info:     Processing Optiresponses.
Info:     Processing Dvprels.
Info:     Processing Opticonstraints.
Info:     Processing Desvarlinks.
Info:     Processing Objectives.
Info:     Processing Opticontrols.
Info:     Processing Optidscreens.
Info:     Processing Tags.
Info:     Processing Dobjrefs.
Info:     Processing Contactsurfs.
Info:     Processing Shapes.
Info:     Processing Ddvals.
Info:     Processing Joints.
Info:     Processing Mechanismconstraints.
Info:     Processing Rigidwalls.
Info:     Processing Failures.
Info:     Processing Crosssections.
Info:     Processing Hourglass.
Info:     Processing Rigidbodies.
Info:     Processing Bodies.
Info:     Processing Mechanisms.
Info:     Processing Transformations.
Info:     Processing Positions.
Info:     Processing Outputrequests.
Info:     Processing Directmatrixinputs.
Info:     Processing Equivalences.
Info:     Processing Solvermasses.
Info:     Processing Analysisparameters.
Info:     Processing Parameters.

Summary:  Feinput finished with 0 errors and 0 warnings.
Info:     Translation Complete.
Info:     Reading OPTISTRUCT from C:/Users/sihol/OneDrive/Desktop/ASE/MATLAB/RESULT FILES/ASE_Project2025_SuperPanel_3787415_redesign.fem using C:\Program Files\Altair\2023.1\hwdesktop\io\model_readers\feinput\bin\win64\optistruct.exe on 07-02-2025 23:41:10.
Info:     Processing Modules.
Info:     Processing Cards.
Info:     Processing System Collectors.
Info:     Processing Systems.
Info:     Processing Nodes.
Info:     Processing Vectorcols.
Info:     Processing Vectors.
Info:     Processing Materials.
Info:     Processing Properties.
Info:     Processing Components.
Info:     Processing Groups.
Info:     Processing Elements.
Info:     Processing Load Collectors.
Info:     Processing Equations.
Info:     Processing Loads.
Info:     Processing Assemblies.
Info:     Processing Curves.
Info:     Processing Blocks.
Info:     Processing Sets.
Info:     Processing Output Blocks.
Info:     Processing Load Steps.
Info:     Processing Sensors.
Info:     Processing Plys.
Info:     Processing Laminates.
Info:     Processing Designvars.
Info:     Processing Beamsectcols.
Info:     Processing Beamsections.
Info:     Processing Optitableentrs.
Info:     Processing Dequations.
Info:     Processing Optiresponses.
Info:     Processing Dvprels.
Info:     Processing Opticonstraints.
Info:     Processing Desvarlinks.
Info:     Processing Objectives.
Info:     Processing Opticontrols.
Info:     Processing Optidscreens.
Info:     Processing Tags.
Info:     Processing Dobjrefs.
Info:     Processing Contactsurfs.
Info:     Processing Shapes.
Info:     Processing Ddvals.
Info:     Processing Joints.
Info:     Processing Mechanismconstraints.
Info:     Processing Rigidwalls.
Info:     Processing Failures.
Info:     Processing Crosssections.
Info:     Processing Hourglass.
Info:     Processing Rigidbodies.
Info:     Processing Bodies.
Info:     Processing Mechanisms.
Info:     Processing Transformations.
Info:     Processing Positions.
Info:     Processing Outputrequests.
Info:     Processing Directmatrixinputs.
Info:     Processing Equivalences.
Info:     Processing Solvermasses.
Info:     Processing Analysisparameters.
Info:     Processing Parameters.

Summary:  Feinput finished with 0 errors and 0 warnings.
Info:     Translation Complete.
Info:     Reading OPTISTRUCT from C:/Users/sihol/OneDrive/Desktop/ASE/MATLAB/RESULT FILES/ASE_Project2025_SuperPanel_3787415_redesign.fem using C:\Program Files\Altair\2023.1\hwdesktop\io\model_readers\feinput\bin\win64\optistruct.exe on 07-02-2025 23:47:36.
Info:     Processing Modules.
Info:     Processing Cards.
Info:     Processing System Collectors.
Info:     Processing Systems.
Info:     Processing Nodes.
Info:     Processing Vectorcols.
Info:     Processing Vectors.
Info:     Processing Materials.
Info:     Processing Properties.
Info:     Processing Components.
Info:     Processing Groups.
Info:     Processing Elements.
Info:     Processing Load Collectors.
Info:     Processing Equations.
Info:     Processing Loads.
Info:     Processing Assemblies.
Info:     Processing Curves.
Info:     Processing Blocks.
Info:     Processing Sets.
Info:     Processing Output Blocks.
Info:     Processing Load Steps.
Info:     Processing Sensors.
Info:     Processing Plys.
Info:     Processing Laminates.
Info:     Processing Designvars.
Info:     Processing Beamsectcols.
Info:     Processing Beamsections.
Info:     Processing Optitableentrs.
Info:     Processing Dequations.
Info:     Processing Optiresponses.
Info:     Processing Dvprels.
Info:     Processing Opticonstraints.
Info:     Processing Desvarlinks.
Info:     Processing Objectives.
Info:     Processing Opticontrols.
Info:     Processing Optidscreens.
Info:     Processing Tags.
Info:     Processing Dobjrefs.
Info:     Processing Contactsurfs.
Info:     Processing Shapes.
Info:     Processing Ddvals.
Info:     Processing Joints.
Info:     Processing Mechanismconstraints.
Info:     Processing Rigidwalls.
Info:     Processing Failures.
Info:     Processing Crosssections.
Info:     Processing Hourglass.
Info:     Processing Rigidbodies.
Info:     Processing Bodies.
Info:     Processing Mechanisms.
Info:     Processing Transformations.
Info:     Processing Positions.
Info:     Processing Outputrequests.
Info:     Processing Directmatrixinputs.
Info:     Processing Equivalences.
Info:     Processing Solvermasses.
Info:     Processing Analysisparameters.
Info:     Processing Parameters.

Summary:  Feinput finished with 0 errors and 0 warnings.
Info:     Translation Complete.
Info:     Reading OPTISTRUCT from C:/Users/sihol/OneDrive/Desktop/ASE/MATLAB/RESULT FILES/ASE_Project2025_SuperPanel_3787415_redesign.fem using C:\Program Files\Altair\2023.1\hwdesktop\io\model_readers\feinput\bin\win64\optistruct.exe on 07-02-2025 23:57:09.
Info:     Processing Modules.
Info:     Processing Cards.
Info:     Processing System Collectors.
Info:     Processing Systems.
Info:     Processing Nodes.
Info:     Processing Vectorcols.
Info:     Processing Vectors.
Info:     Processing Materials.
Info:     Processing Properties.
Info:     Processing Components.
Info:     Processing Groups.
Info:     Processing Elements.
Info:     Processing Load Collectors.
Info:     Processing Equations.
Info:     Processing Loads.
Info:     Processing Assemblies.
Info:     Processing Curves.
Info:     Processing Blocks.
Info:     Processing Sets.
Info:     Processing Output Blocks.
Info:     Processing Load Steps.
Info:     Processing Sensors.
Info:     Processing Plys.
Info:     Processing Laminates.
Info:     Processing Designvars.
Info:     Processing Beamsectcols.
Info:     Processing Beamsections.
Info:     Processing Optitableentrs.
Info:     Processing Dequations.
Info:     Processing Optiresponses.
Info:     Processing Dvprels.
Info:     Processing Opticonstraints.
Info:     Processing Desvarlinks.
Info:     Processing Objectives.
Info:     Processing Opticontrols.
Info:     Processing Optidscreens.
Info:     Processing Tags.
Info:     Processing Dobjrefs.
Info:     Processing Contactsurfs.
Info:     Processing Shapes.
Info:     Processing Ddvals.
Info:     Processing Joints.
Info:     Processing Mechanismconstraints.
Info:     Processing Rigidwalls.
Info:     Processing Failures.
Info:     Processing Crosssections.
Info:     Processing Hourglass.
Info:     Processing Rigidbodies.
Info:     Processing Bodies.
Info:     Processing Mechanisms.
Info:     Processing Transformations.
Info:     Processing Positions.
Info:     Processing Outputrequests.
Info:     Processing Directmatrixinputs.
Info:     Processing Equivalences.
Info:     Processing Solvermasses.
Info:     Processing Analysisparameters.
Info:     Processing Parameters.

Summary:  Feinput finished with 0 errors and 0 warnings.
Info:     Translation Complete.
Info:     Reading OPTISTRUCT from C:/Users/sihol/OneDrive/Desktop/ASE/MATLAB/RESULT FILES/ASE_Project2025_SuperPanel_3787415_redesign.fem using C:\Program Files\Altair\2023.1\hwdesktop\io\model_readers\feinput\bin\win64\optistruct.exe on 07-02-2025 23:58:11.
Info:     Processing Modules.
Info:     Processing Cards.
Info:     Processing System Collectors.
Info:     Processing Systems.
Info:     Processing Nodes.
Info:     Processing Vectorcols.
Info:     Processing Vectors.
Info:     Processing Materials.
Info:     Processing Properties.
Info:     Processing Components.
Info:     Processing Groups.
Info:     Processing Elements.
Info:     Processing Load Collectors.
Info:     Processing Equations.
Info:     Processing Loads.
Info:     Processing Assemblies.
Info:     Processing Curves.
Info:     Processing Blocks.
Info:     Processing Sets.
Info:     Processing Output Blocks.
Info:     Processing Load Steps.
Info:     Processing Sensors.
Info:     Processing Plys.
Info:     Processing Laminates.
Info:     Processing Designvars.
Info:     Processing Beamsectcols.
Info:     Processing Beamsections.
Info:     Processing Optitableentrs.
Info:     Processing Dequations.
Info:     Processing Optiresponses.
Info:     Processing Dvprels.
Info:     Processing Opticonstraints.
Info:     Processing Desvarlinks.
Info:     Processing Objectives.
Info:     Processing Opticontrols.
Info:     Processing Optidscreens.
Info:     Processing Tags.
Info:     Processing Dobjrefs.
Info:     Processing Contactsurfs.
Info:     Processing Shapes.
Info:     Processing Ddvals.
Info:     Processing Joints.
Info:     Processing Mechanismconstraints.
Info:     Processing Rigidwalls.
Info:     Processing Failures.
Info:     Processing Crosssections.
Info:     Processing Hourglass.
Info:     Processing Rigidbodies.
Info:     Processing Bodies.
Info:     Processing Mechanisms.
Info:     Processing Transformations.
Info:     Processing Positions.
Info:     Processing Outputrequests.
Info:     Processing Directmatrixinputs.
Info:     Processing Equivalences.
Info:     Processing Solvermasses.
Info:     Processing Analysisparameters.
Info:     Processing Parameters.

Summary:  Feinput finished with 0 errors and 0 warnings.
Info:     Translation Complete.
Info:     Reading OPTISTRUCT from C:/Users/sihol/OneDrive/Desktop/ASE/MATLAB/RESULT FILES/ASE_Project2025_SuperPanel_3787415_redesign.fem using C:\Program Files\Altair\2023.1\hwdesktop\io\model_readers\feinput\bin\win64\optistruct.exe on 07-03-2025 00:04:37.
Info:     Processing Modules.
Info:     Processing Cards.
Info:     Processing System Collectors.
Info:     Processing Systems.
Info:     Processing Nodes.
Info:     Processing Vectorcols.
Info:     Processing Vectors.
Info:     Processing Materials.
Info:     Processing Properties.
Info:     Processing Components.
Info:     Processing Groups.
Info:     Processing Elements.
Info:     Processing Load Collectors.
Info:     Processing Equations.
Info:     Processing Loads.
Info:     Processing Assemblies.
Info:     Processing Curves.
Info:     Processing Blocks.
Info:     Processing Sets.
Info:     Processing Output Blocks.
Info:     Processing Load Steps.
Info:     Processing Sensors.
Info:     Processing Plys.
Info:     Processing Laminates.
Info:     Processing Designvars.
Info:     Processing Beamsectcols.
Info:     Processing Beamsections.
Info:     Processing Optitableentrs.
Info:     Processing Dequations.
Info:     Processing Optiresponses.
Info:     Processing Dvprels.
Info:     Processing Opticonstraints.
Info:     Processing Desvarlinks.
Info:     Processing Objectives.
Info:     Processing Opticontrols.
Info:     Processing Optidscreens.
Info:     Processing Tags.
Info:     Processing Dobjrefs.
Info:     Processing Contactsurfs.
Info:     Processing Shapes.
Info:     Processing Ddvals.
Info:     Processing Joints.
Info:     Processing Mechanismconstraints.
Info:     Processing Rigidwalls.
Info:     Processing Failures.
Info:     Processing Crosssections.
Info:     Processing Hourglass.
Info:     Processing Rigidbodies.
Info:     Processing Bodies.
Info:     Processing Mechanisms.
Info:     Processing Transformations.
Info:     Processing Positions.
Info:     Processing Outputrequests.
Info:     Processing Directmatrixinputs.
Info:     Processing Equivalences.
Info:     Processing Solvermasses.
Info:     Processing Analysisparameters.
Info:     Processing Parameters.

Summary:  Feinput finished with 0 errors and 0 warnings.
Info:     Translation Complete.
Info:     Reading OPTISTRUCT from C:/Users/sihol/OneDrive/Desktop/ASE/MATLAB/RESULT FILES/ASE_Project2025_SuperPanel_3787415_redesign.fem using C:\Program Files\Altair\2023.1\hwdesktop\io\model_readers\feinput\bin\win64\optistruct.exe on 07-03-2025 00:13:01.
Info:     Processing Modules.
Info:     Processing Cards.
Info:     Processing System Collectors.
Info:     Processing Systems.
Info:     Processing Nodes.
Info:     Processing Vectorcols.
Info:     Processing Vectors.
Info:     Processing Materials.
Info:     Processing Properties.
Info:     Processing Components.
Info:     Processing Groups.
Info:     Processing Elements.
Info:     Processing Load Collectors.
Info:     Processing Equations.
Info:     Processing Loads.
Info:     Processing Assemblies.
Info:     Processing Curves.
Info:     Processing Blocks.
Info:     Processing Sets.
Info:     Processing Output Blocks.
Info:     Processing Load Steps.
Info:     Processing Sensors.
Info:     Processing Plys.
Info:     Processing Laminates.
Info:     Processing Designvars.
Info:     Processing Beamsectcols.
Info:     Processing Beamsections.
Info:     Processing Optitableentrs.
Info:     Processing Dequations.
Info:     Processing Optiresponses.
Info:     Processing Dvprels.
Info:     Processing Opticonstraints.
Info:     Processing Desvarlinks.
Info:     Processing Objectives.
Info:     Processing Opticontrols.
Info:     Processing Optidscreens.
Info:     Processing Tags.
Info:     Processing Dobjrefs.
Info:     Processing Contactsurfs.
Info:     Processing Shapes.
Info:     Processing Ddvals.
Info:     Processing Joints.
Info:     Processing Mechanismconstraints.
Info:     Processing Rigidwalls.
Info:     Processing Failures.
Info:     Processing Crosssections.
Info:     Processing Hourglass.
Info:     Processing Rigidbodies.
Info:     Processing Bodies.
Info:     Processing Mechanisms.
Info:     Processing Transformations.
Info:     Processing Positions.
Info:     Processing Outputrequests.
Info:     Processing Directmatrixinputs.
Info:     Processing Equivalences.
Info:     Processing Solvermasses.
Info:     Processing Analysisparameters.
Info:     Processing Parameters.

Summary:  Feinput finished with 0 errors and 0 warnings.
Info:     Translation Complete.
Info:     Reading OPTISTRUCT from C:/Users/sihol/OneDrive/Desktop/ASE/MATLAB/RESULT FILES/ASE_Project2025_SuperPanel_3787415_redesign.fem using C:\Program Files\Altair\2023.1\hwdesktop\io\model_readers\feinput\bin\win64\optistruct.exe on 07-03-2025 00:28:30.
Info:     Processing Modules.
Info:     Processing Cards.
Info:     Processing System Collectors.
Info:     Processing Systems.
Info:     Processing Nodes.
Info:     Processing Vectorcols.
Info:     Processing Vectors.
Info:     Processing Materials.
Info:     Processing Properties.
Info:     Processing Components.
Info:     Processing Groups.
Info:     Processing Elements.
Info:     Processing Load Collectors.
Info:     Processing Equations.
Info:     Processing Loads.
Info:     Processing Assemblies.
Info:     Processing Curves.
Info:     Processing Blocks.
Info:     Processing Sets.
Info:     Processing Output Blocks.
Info:     Processing Load Steps.
Info:     Processing Sensors.
Info:     Processing Plys.
Info:     Processing Laminates.
Info:     Processing Designvars.
Info:     Processing Beamsectcols.
Info:     Processing Beamsections.
Info:     Processing Optitableentrs.
Info:     Processing Dequations.
Info:     Processing Optiresponses.
Info:     Processing Dvprels.
Info:     Processing Opticonstraints.
Info:     Processing Desvarlinks.
Info:     Processing Objectives.
Info:     Processing Opticontrols.
Info:     Processing Optidscreens.
Info:     Processing Tags.
Info:     Processing Dobjrefs.
Info:     Processing Contactsurfs.
Info:     Processing Shapes.
Info:     Processing Ddvals.
Info:     Processing Joints.
Info:     Processing Mechanismconstraints.
Info:     Processing Rigidwalls.
Info:     Processing Failures.
Info:     Processing Crosssections.
Info:     Processing Hourglass.
Info:     Processing Rigidbodies.
Info:     Processing Bodies.
Info:     Processing Mechanisms.
Info:     Processing Transformations.
Info:     Processing Positions.
Info:     Processing Outputrequests.
Info:     Processing Directmatrixinputs.
Info:     Processing Equivalences.
Info:     Processing Solvermasses.
Info:     Processing Analysisparameters.
Info:     Processing Parameters.

Summary:  Feinput finished with 0 errors and 0 warnings.
Info:     Translation Complete.
Info:     Reading OPTISTRUCT from C:/Users/sihol/OneDrive/Desktop/ASE/MATLAB/RESULT FILES/ASE_Project2025_SuperPanel_3787415_redesign.fem using C:\Program Files\Altair\2023.1\hwdesktop\io\model_readers\feinput\bin\win64\optistruct.exe on 07-03-2025 00:34:10.
Info:     Processing Modules.
Info:     Processing Cards.
Info:     Processing System Collectors.
Info:     Processing Systems.
Info:     Processing Nodes.
Info:     Processing Vectorcols.
Info:     Processing Vectors.
Info:     Processing Materials.
Info:     Processing Properties.
Info:     Processing Components.
Info:     Processing Groups.
Info:     Processing Elements.
Info:     Processing Load Collectors.
Info:     Processing Equations.
Info:     Processing Loads.
Info:     Processing Assemblies.
Info:     Processing Curves.
Info:     Processing Blocks.
Info:     Processing Sets.
Info:     Processing Output Blocks.
Info:     Processing Load Steps.
Info:     Processing Sensors.
Info:     Processing Plys.
Info:     Processing Laminates.
Info:     Processing Designvars.
Info:     Processing Beamsectcols.
Info:     Processing Beamsections.
Info:     Processing Optitableentrs.
Info:     Processing Dequations.
Info:     Processing Optiresponses.
Info:     Processing Dvprels.
Info:     Processing Opticonstraints.
Info:     Processing Desvarlinks.
Info:     Processing Objectives.
Info:     Processing Opticontrols.
Info:     Processing Optidscreens.
Info:     Processing Tags.
Info:     Processing Dobjrefs.
Info:     Processing Contactsurfs.
Info:     Processing Shapes.
Info:     Processing Ddvals.
Info:     Processing Joints.
Info:     Processing Mechanismconstraints.
Info:     Processing Rigidwalls.
Info:     Processing Failures.
Info:     Processing Crosssections.
Info:     Processing Hourglass.
Info:     Processing Rigidbodies.
Info:     Processing Bodies.
Info:     Processing Mechanisms.
Info:     Processing Transformations.
Info:     Processing Positions.
Info:     Processing Outputrequests.
Info:     Processing Directmatrixinputs.
Info:     Processing Equivalences.
Info:     Processing Solvermasses.
Info:     Processing Analysisparameters.
Info:     Processing Parameters.

Summary:  Feinput finished with 0 errors and 0 warnings.
Info:     Translation Complete.
Info:     Reading OPTISTRUCT from C:/Users/sihol/OneDrive/Desktop/ASE/MATLAB/RESULT FILES/ASE_Project2025_SuperPanel_3787415_redesign.fem using C:\Program Files\Altair\2023.1\hwdesktop\io\model_readers\feinput\bin\win64\optistruct.exe on 07-03-2025 00:40:10.
Info:     Processing Modules.
Info:     Processing Cards.
Info:     Processing System Collectors.
Info:     Processing Systems.
Info:     Processing Nodes.
Info:     Processing Vectorcols.
Info:     Processing Vectors.
Info:     Processing Materials.
Info:     Processing Properties.
Info:     Processing Components.
Info:     Processing Groups.
Info:     Processing Elements.
Info:     Processing Load Collectors.
Info:     Processing Equations.
Info:     Processing Loads.
Info:     Processing Assemblies.
Info:     Processing Curves.
Info:     Processing Blocks.
Info:     Processing Sets.
Info:     Processing Output Blocks.
Info:     Processing Load Steps.
Info:     Processing Sensors.
Info:     Processing Plys.
Info:     Processing Laminates.
Info:     Processing Designvars.
Info:     Processing Beamsectcols.
Info:     Processing Beamsections.
Info:     Processing Optitableentrs.
Info:     Processing Dequations.
Info:     Processing Optiresponses.
Info:     Processing Dvprels.
Info:     Processing Opticonstraints.
Info:     Processing Desvarlinks.
Info:     Processing Objectives.
Info:     Processing Opticontrols.
Info:     Processing Optidscreens.
Info:     Processing Tags.
Info:     Processing Dobjrefs.
Info:     Processing Contactsurfs.
Info:     Processing Shapes.
Info:     Processing Ddvals.
Info:     Processing Joints.
Info:     Processing Mechanismconstraints.
Info:     Processing Rigidwalls.
Info:     Processing Failures.
Info:     Processing Crosssections.
Info:     Processing Hourglass.
Info:     Processing Rigidbodies.
Info:     Processing Bodies.
Info:     Processing Mechanisms.
Info:     Processing Transformations.
Info:     Processing Positions.
Info:     Processing Outputrequests.
Info:     Processing Directmatrixinputs.
Info:     Processing Equivalences.
Info:     Processing Solvermasses.
Info:     Processing Analysisparameters.
Info:     Processing Parameters.

Summary:  Feinput finished with 0 errors and 0 warnings.
Info:     Translation Complete.
Info:     Reading OPTISTRUCT from C:/Users/sihol/OneDrive/Desktop/ASE/MATLAB/RESULT FILES/ASE_Project2025_SuperPanel_3787415_redesign.fem using C:\Program Files\Altair\2023.1\hwdesktop\io\model_readers\feinput\bin\win64\optistruct.exe on 07-03-2025 00:51:07.
Info:     Processing Modules.
Info:     Processing Cards.
Info:     Processing System Collectors.
Info:     Processing Systems.
Info:     Processing Nodes.
Info:     Processing Vectorcols.
Info:     Processing Vectors.
Info:     Processing Materials.
Info:     Processing Properties.
Info:     Processing Components.
Info:     Processing Groups.
Info:     Processing Elements.
Info:     Processing Load Collectors.
Info:     Processing Equations.
Info:     Processing Loads.
Info:     Processing Assemblies.
Info:     Processing Curves.
Info:     Processing Blocks.
Info:     Processing Sets.
Info:     Processing Output Blocks.
Info:     Processing Load Steps.
Info:     Processing Sensors.
Info:     Processing Plys.
Info:     Processing Laminates.
Info:     Processing Designvars.
Info:     Processing Beamsectcols.
Info:     Processing Beamsections.
Info:     Processing Optitableentrs.
Info:     Processing Dequations.
Info:     Processing Optiresponses.
Info:     Processing Dvprels.
Info:     Processing Opticonstraints.
Info:     Processing Desvarlinks.
Info:     Processing Objectives.
Info:     Processing Opticontrols.
Info:     Processing Optidscreens.
Info:     Processing Tags.
Info:     Processing Dobjrefs.
Info:     Processing Contactsurfs.
Info:     Processing Shapes.
Info:     Processing Ddvals.
Info:     Processing Joints.
Info:     Processing Mechanismconstraints.
Info:     Processing Rigidwalls.
Info:     Processing Failures.
Info:     Processing Crosssections.
Info:     Processing Hourglass.
Info:     Processing Rigidbodies.
Info:     Processing Bodies.
Info:     Processing Mechanisms.
Info:     Processing Transformations.
Info:     Processing Positions.
Info:     Processing Outputrequests.
Info:     Processing Directmatrixinputs.
Info:     Processing Equivalences.
Info:     Processing Solvermasses.
Info:     Processing Analysisparameters.
Info:     Processing Parameters.

Summary:  Feinput finished with 0 errors and 0 warnings.
Info:     Translation Complete.
Info:     Reading OPTISTRUCT from C:/Users/sihol/OneDrive/Desktop/ASE/MATLAB/RESULT FILES/ASE_Project2025_SuperPanel_3787415_redesign.fem using C:\Program Files\Altair\2023.1\hwdesktop\io\model_readers\feinput\bin\win64\optistruct.exe on 07-03-2025 00:52:37.
Info:     Processing Modules.
Info:     Processing Cards.
Info:     Processing System Collectors.
Info:     Processing Systems.
Info:     Processing Nodes.
Info:     Processing Vectorcols.
Info:     Processing Vectors.
Info:     Processing Materials.
Info:     Processing Properties.
Info:     Processing Components.
Info:     Processing Groups.
Info:     Processing Elements.
Info:     Processing Load Collectors.
Info:     Processing Equations.
Info:     Processing Loads.
Info:     Processing Assemblies.
Info:     Processing Curves.
Info:     Processing Blocks.
Info:     Processing Sets.
Info:     Processing Output Blocks.
Info:     Processing Load Steps.
Info:     Processing Sensors.
Info:     Processing Plys.
Info:     Processing Laminates.
Info:     Processing Designvars.
Info:     Processing Beamsectcols.
Info:     Processing Beamsections.
Info:     Processing Optitableentrs.
Info:     Processing Dequations.
Info:     Processing Optiresponses.
Info:     Processing Dvprels.
Info:     Processing Opticonstraints.
Info:     Processing Desvarlinks.
Info:     Processing Objectives.
Info:     Processing Opticontrols.
Info:     Processing Optidscreens.
Info:     Processing Tags.
Info:     Processing Dobjrefs.
Info:     Processing Contactsurfs.
Info:     Processing Shapes.
Info:     Processing Ddvals.
Info:     Processing Joints.
Info:     Processing Mechanismconstraints.
Info:     Processing Rigidwalls.
Info:     Processing Failures.
Info:     Processing Crosssections.
Info:     Processing Hourglass.
Info:     Processing Rigidbodies.
Info:     Processing Bodies.
Info:     Processing Mechanisms.
Info:     Processing Transformations.
Info:     Processing Positions.
Info:     Processing Outputrequests.
Info:     Processing Directmatrixinputs.
Info:     Processing Equivalences.
Info:     Processing Solvermasses.
Info:     Processing Analysisparameters.
Info:     Processing Parameters.

Summary:  Feinput finished with 0 errors and 0 warnings.
Info:     Translation Complete.
Info:     Reading OPTISTRUCT from C:/Users/sihol/OneDrive/Desktop/ASE/MATLAB/RESULT FILES/ASE_Project2025_SuperPanel_3787415_redesign.fem using C:\Program Files\Altair\2023.1\hwdesktop\io\model_readers\feinput\bin\win64\optistruct.exe on 07-03-2025 00:53:01.
Info:     Processing Modules.
Info:     Processing Cards.
Info:     Processing System Collectors.
Info:     Processing Systems.
Info:     Processing Nodes.
Info:     Processing Vectorcols.
Info:     Processing Vectors.
Info:     Processing Materials.
Info:     Processing Properties.
Info:     Processing Components.
Info:     Processing Groups.
Info:     Processing Elements.
Info:     Processing Load Collectors.
Info:     Processing Equations.
Info:     Processing Loads.
Info:     Processing Assemblies.
Info:     Processing Curves.
Info:     Processing Blocks.
Info:     Processing Sets.
Info:     Processing Output Blocks.
Info:     Processing Load Steps.
Info:     Processing Sensors.
Info:     Processing Plys.
Info:     Processing Laminates.
Info:     Processing Designvars.
Info:     Processing Beamsectcols.
Info:     Processing Beamsections.
Info:     Processing Optitableentrs.
Info:     Processing Dequations.
Info:     Processing Optiresponses.
Info:     Processing Dvprels.
Info:     Processing Opticonstraints.
Info:     Processing Desvarlinks.
Info:     Processing Objectives.
Info:     Processing Opticontrols.
Info:     Processing Optidscreens.
Info:     Processing Tags.
Info:     Processing Dobjrefs.
Info:     Processing Contactsurfs.
Info:     Processing Shapes.
Info:     Processing Ddvals.
Info:     Processing Joints.
Info:     Processing Mechanismconstraints.
Info:     Processing Rigidwalls.
Info:     Processing Failures.
Info:     Processing Crosssections.
Info:     Processing Hourglass.
Info:     Processing Rigidbodies.
Info:     Processing Bodies.
Info:     Processing Mechanisms.
Info:     Processing Transformations.
Info:     Processing Positions.
Info:     Processing Outputrequests.
Info:     Processing Directmatrixinputs.
Info:     Processing Equivalences.
Info:     Processing Solvermasses.
Info:     Processing Analysisparameters.
Info:     Processing Parameters.

Summary:  Feinput finished with 0 errors and 0 warnings.
Info:     Translation Complete.
Info:     Reading OPTISTRUCT from C:/Users/sihol/OneDrive/Desktop/ASE/MATLAB/RESULT FILES/ASE_Project2025_SuperPanel_3787415_redesign.fem using C:\Program Files\Altair\2023.1\hwdesktop\io\model_readers\feinput\bin\win64\optistruct.exe on 07-03-2025 00:55:20.
Info:     Processing Modules.
Info:     Processing Cards.
Info:     Processing System Collectors.
Info:     Processing Systems.
Info:     Processing Nodes.
Info:     Processing Vectorcols.
Info:     Processing Vectors.
Info:     Processing Materials.
Info:     Processing Properties.
Info:     Processing Components.
Info:     Processing Groups.
Info:     Processing Elements.
Info:     Processing Load Collectors.
Info:     Processing Equations.
Info:     Processing Loads.
Info:     Processing Assemblies.
Info:     Processing Curves.
Info:     Processing Blocks.
Info:     Processing Sets.
Info:     Processing Output Blocks.
Info:     Processing Load Steps.
Info:     Processing Sensors.
Info:     Processing Plys.
Info:     Processing Laminates.
Info:     Processing Designvars.
Info:     Processing Beamsectcols.
Info:     Processing Beamsections.
Info:     Processing Optitableentrs.
Info:     Processing Dequations.
Info:     Processing Optiresponses.
Info:     Processing Dvprels.
Info:     Processing Opticonstraints.
Info:     Processing Desvarlinks.
Info:     Processing Objectives.
Info:     Processing Opticontrols.
Info:     Processing Optidscreens.
Info:     Processing Tags.
Info:     Processing Dobjrefs.
Info:     Processing Contactsurfs.
Info:     Processing Shapes.
Info:     Processing Ddvals.
Info:     Processing Joints.
Info:     Processing Mechanismconstraints.
Info:     Processing Rigidwalls.
Info:     Processing Failures.
Info:     Processing Crosssections.
Info:     Processing Hourglass.
Info:     Processing Rigidbodies.
Info:     Processing Bodies.
Info:     Processing Mechanisms.
Info:     Processing Transformations.
Info:     Processing Positions.
Info:     Processing Outputrequests.
Info:     Processing Directmatrixinputs.
Info:     Processing Equivalences.
Info:     Processing Solvermasses.
Info:     Processing Analysisparameters.
Info:     Processing Parameters.

Summary:  Feinput finished with 0 errors and 0 warnings.
Info:     Translation Complete.
Info:     Reading OPTISTRUCT from C:/Users/sihol/OneDrive/Desktop/ASE/MATLAB/RESULT FILES/ASE_Project2025_SuperPanel_3787415_redesign.fem using C:\Program Files\Altair\2023.1\hwdesktop\io\model_readers\feinput\bin\win64\optistruct.exe on 07-03-2025 00:56:22.
Info:     Processing Modules.
Info:     Processing Cards.
Info:     Processing System Collectors.
Info:     Processing Systems.
Info:     Processing Nodes.
Info:     Processing Vectorcols.
Info:     Processing Vectors.
Info:     Processing Materials.
Info:     Processing Properties.
Info:     Processing Components.
Info:     Processing Groups.
Info:     Processing Elements.
Info:     Processing Load Collectors.
Info:     Processing Equations.
Info:     Processing Loads.
Info:     Processing Assemblies.
Info:     Processing Curves.
Info:     Processing Blocks.
Info:     Processing Sets.
Info:     Processing Output Blocks.
Info:     Processing Load Steps.
Info:     Processing Sensors.
Info:     Processing Plys.
Info:     Processing Laminates.
Info:     Processing Designvars.
Info:     Processing Beamsectcols.
Info:     Processing Beamsections.
Info:     Processing Optitableentrs.
Info:     Processing Dequations.
Info:     Processing Optiresponses.
Info:     Processing Dvprels.
Info:     Processing Opticonstraints.
Info:     Processing Desvarlinks.
Info:     Processing Objectives.
Info:     Processing Opticontrols.
Info:     Processing Optidscreens.
Info:     Processing Tags.
Info:     Processing Dobjrefs.
Info:     Processing Contactsurfs.
Info:     Processing Shapes.
Info:     Processing Ddvals.
Info:     Processing Joints.
Info:     Processing Mechanismconstraints.
Info:     Processing Rigidwalls.
Info:     Processing Failures.
Info:     Processing Crosssections.
Info:     Processing Hourglass.
Info:     Processing Rigidbodies.
Info:     Processing Bodies.
Info:     Processing Mechanisms.
Info:     Processing Transformations.
Info:     Processing Positions.
Info:     Processing Outputrequests.
Info:     Processing Directmatrixinputs.
Info:     Processing Equivalences.
Info:     Processing Solvermasses.
Info:     Processing Analysisparameters.
Info:     Processing Parameters.

Summary:  Feinput finished with 0 errors and 0 warnings.
Info:     Translation Complete.
Info:     Reading OPTISTRUCT from C:/Users/sihol/OneDrive/Desktop/ASE/MATLAB/RESULT FILES/ASE_Project2025_SuperPanel_3787415_redesign.fem using C:\Program Files\Altair\2023.1\hwdesktop\io\model_readers\feinput\bin\win64\optistruct.exe on 07-03-2025 00:56:49.
Info:     Processing Modules.
Info:     Processing Cards.
Info:     Processing System Collectors.
Info:     Processing Systems.
Info:     Processing Nodes.
Info:     Processing Vectorcols.
Info:     Processing Vectors.
Info:     Processing Materials.
Info:     Processing Properties.
Info:     Processing Components.
Info:     Processing Groups.
Info:     Processing Elements.
Info:     Processing Load Collectors.
Info:     Processing Equations.
Info:     Processing Loads.
Info:     Processing Assemblies.
Info:     Processing Curves.
Info:     Processing Blocks.
Info:     Processing Sets.
Info:     Processing Output Blocks.
Info:     Processing Load Steps.
Info:     Processing Sensors.
Info:     Processing Plys.
Info:     Processing Laminates.
Info:     Processing Designvars.
Info:     Processing Beamsectcols.
Info:     Processing Beamsections.
Info:     Processing Optitableentrs.
Info:     Processing Dequations.
Info:     Processing Optiresponses.
Info:     Processing Dvprels.
Info:     Processing Opticonstraints.
Info:     Processing Desvarlinks.
Info:     Processing Objectives.
Info:     Processing Opticontrols.
Info:     Processing Optidscreens.
Info:     Processing Tags.
Info:     Processing Dobjrefs.
Info:     Processing Contactsurfs.
Info:     Processing Shapes.
Info:     Processing Ddvals.
Info:     Processing Joints.
Info:     Processing Mechanismconstraints.
Info:     Processing Rigidwalls.
Info:     Processing Failures.
Info:     Processing Crosssections.
Info:     Processing Hourglass.
Info:     Processing Rigidbodies.
Info:     Processing Bodies.
Info:     Processing Mechanisms.
Info:     Processing Transformations.
Info:     Processing Positions.
Info:     Processing Outputrequests.
Info:     Processing Directmatrixinputs.
Info:     Processing Equivalences.
Info:     Processing Solvermasses.
Info:     Processing Analysisparameters.
Info:     Processing Parameters.

Summary:  Feinput finished with 0 errors and 0 warnings.
Info:     Translation Complete.
Info:     Reading OPTISTRUCT from C:/Users/sihol/OneDrive/Desktop/ASE/MATLAB/RESULT FILES/ASE_Project2025_SuperPanel_3787415_redesign.fem using C:\Program Files\Altair\2023.1\hwdesktop\io\model_readers\feinput\bin\win64\optistruct.exe on 07-03-2025 01:00:13.
Info:     Processing Modules.
Info:     Processing Cards.
Info:     Processing System Collectors.
Info:     Processing Systems.
Info:     Processing Nodes.
Info:     Processing Vectorcols.
Info:     Processing Vectors.
Info:     Processing Materials.
Info:     Processing Properties.
Info:     Processing Components.
Info:     Processing Groups.
Info:     Processing Elements.
Info:     Processing Load Collectors.
Info:     Processing Equations.
Info:     Processing Loads.
Info:     Processing Assemblies.
Info:     Processing Curves.
Info:     Processing Blocks.
Info:     Processing Sets.
Info:     Processing Output Blocks.
Info:     Processing Load Steps.
Info:     Processing Sensors.
Info:     Processing Plys.
Info:     Processing Laminates.
Info:     Processing Designvars.
Info:     Processing Beamsectcols.
Info:     Processing Beamsections.
Info:     Processing Optitableentrs.
Info:     Processing Dequations.
Info:     Processing Optiresponses.
Info:     Processing Dvprels.
Info:     Processing Opticonstraints.
Info:     Processing Desvarlinks.
Info:     Processing Objectives.
Info:     Processing Opticontrols.
Info:     Processing Optidscreens.
Info:     Processing Tags.
Info:     Processing Dobjrefs.
Info:     Processing Contactsurfs.
Info:     Processing Shapes.
Info:     Processing Ddvals.
Info:     Processing Joints.
Info:     Processing Mechanismconstraints.
Info:     Processing Rigidwalls.
Info:     Processing Failures.
Info:     Processing Crosssections.
Info:     Processing Hourglass.
Info:     Processing Rigidbodies.
Info:     Processing Bodies.
Info:     Processing Mechanisms.
Info:     Processing Transformations.
Info:     Processing Positions.
Info:     Processing Outputrequests.
Info:     Processing Directmatrixinputs.
Info:     Processing Equivalences.
Info:     Processing Solvermasses.
Info:     Processing Analysisparameters.
Info:     Processing Parameters.

Summary:  Feinput finished with 0 errors and 0 warnings.
Info:     Translation Complete.
Info:     Reading OPTISTRUCT from C:/Users/sihol/OneDrive/Desktop/ASE/MATLAB/RESULT FILES/ASE_Project2025_SuperPanel_3787415_redesign.fem using C:\Program Files\Altair\2023.1\hwdesktop\io\model_readers\feinput\bin\win64\optistruct.exe on 07-03-2025 01:00:35.
Info:     Processing Modules.
Info:     Processing Cards.
Info:     Processing System Collectors.
Info:     Processing Systems.
Info:     Processing Nodes.
Info:     Processing Vectorcols.
Info:     Processing Vectors.
Info:     Processing Materials.
Info:     Processing Properties.
Info:     Processing Components.
Info:     Processing Groups.
Info:     Processing Elements.
Info:     Processing Load Collectors.
Info:     Processing Equations.
Info:     Processing Loads.
Info:     Processing Assemblies.
Info:     Processing Curves.
Info:     Processing Blocks.
Info:     Processing Sets.
Info:     Processing Output Blocks.
Info:     Processing Load Steps.
Info:     Processing Sensors.
Info:     Processing Plys.
Info:     Processing Laminates.
Info:     Processing Designvars.
Info:     Processing Beamsectcols.
Info:     Processing Beamsections.
Info:     Processing Optitableentrs.
Info:     Processing Dequations.
Info:     Processing Optiresponses.
Info:     Processing Dvprels.
Info:     Processing Opticonstraints.
Info:     Processing Desvarlinks.
Info:     Processing Objectives.
Info:     Processing Opticontrols.
Info:     Processing Optidscreens.
Info:     Processing Tags.
Info:     Processing Dobjrefs.
Info:     Processing Contactsurfs.
Info:     Processing Shapes.
Info:     Processing Ddvals.
Info:     Processing Joints.
Info:     Processing Mechanismconstraints.
Info:     Processing Rigidwalls.
Info:     Processing Failures.
Info:     Processing Crosssections.
Info:     Processing Hourglass.
Info:     Processing Rigidbodies.
Info:     Processing Bodies.
Info:     Processing Mechanisms.
Info:     Processing Transformations.
Info:     Processing Positions.
Info:     Processing Outputrequests.
Info:     Processing Directmatrixinputs.
Info:     Processing Equivalences.
Info:     Processing Solvermasses.
Info:     Processing Analysisparameters.
Info:     Processing Parameters.

Summary:  Feinput finished with 0 errors and 0 warnings.
Info:     Translation Complete.
Info:     Reading OPTISTRUCT from C:/Users/sihol/OneDrive/Desktop/ASE/MATLAB/RESULT FILES/ASE_Project2025_SuperPanel_3787415_redesign.fem using C:\Program Files\Altair\2023.1\hwdesktop\io\model_readers\feinput\bin\win64\optistruct.exe on 07-03-2025 01:01:55.
Info:     Processing Modules.
Info:     Processing Cards.
Info:     Processing System Collectors.
Info:     Processing Systems.
Info:     Processing Nodes.
Info:     Processing Vectorcols.
Info:     Processing Vectors.
Info:     Processing Materials.
Info:     Processing Properties.
Info:     Processing Components.
Info:     Processing Groups.
Info:     Processing Elements.
Info:     Processing Load Collectors.
Info:     Processing Equations.
Info:     Processing Loads.
Info:     Processing Assemblies.
Info:     Processing Curves.
Info:     Processing Blocks.
Info:     Processing Sets.
Info:     Processing Output Blocks.
Info:     Processing Load Steps.
Info:     Processing Sensors.
Info:     Processing Plys.
Info:     Processing Laminates.
Info:     Processing Designvars.
Info:     Processing Beamsectcols.
Info:     Processing Beamsections.
Info:     Processing Optitableentrs.
Info:     Processing Dequations.
Info:     Processing Optiresponses.
Info:     Processing Dvprels.
Info:     Processing Opticonstraints.
Info:     Processing Desvarlinks.
Info:     Processing Objectives.
Info:     Processing Opticontrols.
Info:     Processing Optidscreens.
Info:     Processing Tags.
Info:     Processing Dobjrefs.
Info:     Processing Contactsurfs.
Info:     Processing Shapes.
Info:     Processing Ddvals.
Info:     Processing Joints.
Info:     Processing Mechanismconstraints.
Info:     Processing Rigidwalls.
Info:     Processing Failures.
Info:     Processing Crosssections.
Info:     Processing Hourglass.
Info:     Processing Rigidbodies.
Info:     Processing Bodies.
Info:     Processing Mechanisms.
Info:     Processing Transformations.
Info:     Processing Positions.
Info:     Processing Outputrequests.
Info:     Processing Directmatrixinputs.
Info:     Processing Equivalences.
Info:     Processing Solvermasses.
Info:     Processing Analysisparameters.
Info:     Processing Parameters.

Summary:  Feinput finished with 0 errors and 0 warnings.
Info:     Translation Complete.
Info:     Reading OPTISTRUCT from C:/Users/sihol/OneDrive/Desktop/ASE/MATLAB/RESULT FILES/ASE_Project2025_SuperPanel_3787415_redesign.fem using C:\Program Files\Altair\2023.1\hwdesktop\io\model_readers\feinput\bin\win64\optistruct.exe on 07-03-2025 01:02:35.
Info:     Processing Modules.
Info:     Processing Cards.
Info:     Processing System Collectors.
Info:     Processing Systems.
Info:     Processing Nodes.
Info:     Processing Vectorcols.
Info:     Processing Vectors.
Info:     Processing Materials.
Info:     Processing Properties.
Info:     Processing Components.
Info:     Processing Groups.
Info:     Processing Elements.
Info:     Processing Load Collectors.
Info:     Processing Equations.
Info:     Processing Loads.
Info:     Processing Assemblies.
Info:     Processing Curves.
Info:     Processing Blocks.
Info:     Processing Sets.
Info:     Processing Output Blocks.
Info:     Processing Load Steps.
Info:     Processing Sensors.
Info:     Processing Plys.
Info:     Processing Laminates.
Info:     Processing Designvars.
Info:     Processing Beamsectcols.
Info:     Processing Beamsections.
Info:     Processing Optitableentrs.
Info:     Processing Dequations.
Info:     Processing Optiresponses.
Info:     Processing Dvprels.
Info:     Processing Opticonstraints.
Info:     Processing Desvarlinks.
Info:     Processing Objectives.
Info:     Processing Opticontrols.
Info:     Processing Optidscreens.
Info:     Processing Tags.
Info:     Processing Dobjrefs.
Info:     Processing Contactsurfs.
Info:     Processing Shapes.
Info:     Processing Ddvals.
Info:     Processing Joints.
Info:     Processing Mechanismconstraints.
Info:     Processing Rigidwalls.
Info:     Processing Failures.
Info:     Processing Crosssections.
Info:     Processing Hourglass.
Info:     Processing Rigidbodies.
Info:     Processing Bodies.
Info:     Processing Mechanisms.
Info:     Processing Transformations.
Info:     Processing Positions.
Info:     Processing Outputrequests.
Info:     Processing Directmatrixinputs.
Info:     Processing Equivalences.
Info:     Processing Solvermasses.
Info:     Processing Analysisparameters.
Info:     Processing Parameters.

Summary:  Feinput finished with 0 errors and 0 warnings.
Info:     Translation Complete.
Info:     Reading OPTISTRUCT from C:/Users/sihol/OneDrive/Desktop/ASE/MATLAB/RESULT FILES/ASE_Project2025_SuperPanel_3787415_redesign.fem using C:\Program Files\Altair\2023.1\hwdesktop\io\model_readers\feinput\bin\win64\optistruct.exe on 07-03-2025 01:05:10.
Info:     Processing Modules.
Info:     Processing Cards.
Info:     Processing System Collectors.
Info:     Processing Systems.
Info:     Processing Nodes.
Info:     Processing Vectorcols.
Info:     Processing Vectors.
Info:     Processing Materials.
Info:     Processing Properties.
Info:     Processing Components.
Info:     Processing Groups.
Info:     Processing Elements.
Info:     Processing Load Collectors.
Info:     Processing Equations.
Info:     Processing Loads.
Info:     Processing Assemblies.
Info:     Processing Curves.
Info:     Processing Blocks.
Info:     Processing Sets.
Info:     Processing Output Blocks.
Info:     Processing Load Steps.
Info:     Processing Sensors.
Info:     Processing Plys.
Info:     Processing Laminates.
Info:     Processing Designvars.
Info:     Processing Beamsectcols.
Info:     Processing Beamsections.
Info:     Processing Optitableentrs.
Info:     Processing Dequations.
Info:     Processing Optiresponses.
Info:     Processing Dvprels.
Info:     Processing Opticonstraints.
Info:     Processing Desvarlinks.
Info:     Processing Objectives.
Info:     Processing Opticontrols.
Info:     Processing Optidscreens.
Info:     Processing Tags.
Info:     Processing Dobjrefs.
Info:     Processing Contactsurfs.
Info:     Processing Shapes.
Info:     Processing Ddvals.
Info:     Processing Joints.
Info:     Processing Mechanismconstraints.
Info:     Processing Rigidwalls.
Info:     Processing Failures.
Info:     Processing Crosssections.
Info:     Processing Hourglass.
Info:     Processing Rigidbodies.
Info:     Processing Bodies.
Info:     Processing Mechanisms.
Info:     Processing Transformations.
Info:     Processing Positions.
Info:     Processing Outputrequests.
Info:     Processing Directmatrixinputs.
Info:     Processing Equivalences.
Info:     Processing Solvermasses.
Info:     Processing Analysisparameters.
Info:     Processing Parameters.

Summary:  Feinput finished with 0 errors and 0 warnings.
Info:     Translation Complete.
Info:     Reading OPTISTRUCT from C:/Users/sihol/OneDrive/Desktop/ASE/MATLAB/RESULT FILES/ASE_Project2025_SuperPanel_3787415_redesign.fem using C:\Program Files\Altair\2023.1\hwdesktop\io\model_readers\feinput\bin\win64\optistruct.exe on 07-03-2025 01:06:19.
Info:     Processing Modules.
Info:     Processing Cards.
Info:     Processing System Collectors.
Info:     Processing Systems.
Info:     Processing Nodes.
Info:     Processing Vectorcols.
Info:     Processing Vectors.
Info:     Processing Materials.
Info:     Processing Properties.
Info:     Processing Components.
Info:     Processing Groups.
Info:     Processing Elements.
Info:     Processing Load Collectors.
Info:     Processing Equations.
Info:     Processing Loads.
Info:     Processing Assemblies.
Info:     Processing Curves.
Info:     Processing Blocks.
Info:     Processing Sets.
Info:     Processing Output Blocks.
Info:     Processing Load Steps.
Info:     Processing Sensors.
Info:     Processing Plys.
Info:     Processing Laminates.
Info:     Processing Designvars.
Info:     Processing Beamsectcols.
Info:     Processing Beamsections.
Info:     Processing Optitableentrs.
Info:     Processing Dequations.
Info:     Processing Optiresponses.
Info:     Processing Dvprels.
Info:     Processing Opticonstraints.
Info:     Processing Desvarlinks.
Info:     Processing Objectives.
Info:     Processing Opticontrols.
Info:     Processing Optidscreens.
Info:     Processing Tags.
Info:     Processing Dobjrefs.
Info:     Processing Contactsurfs.
Info:     Processing Shapes.
Info:     Processing Ddvals.
Info:     Processing Joints.
Info:     Processing Mechanismconstraints.
Info:     Processing Rigidwalls.
Info:     Processing Failures.
Info:     Processing Crosssections.
Info:     Processing Hourglass.
Info:     Processing Rigidbodies.
Info:     Processing Bodies.
Info:     Processing Mechanisms.
Info:     Processing Transformations.
Info:     Processing Positions.
Info:     Processing Outputrequests.
Info:     Processing Directmatrixinputs.
Info:     Processing Equivalences.
Info:     Processing Solvermasses.
Info:     Processing Analysisparameters.
Info:     Processing Parameters.

Summary:  Feinput finished with 0 errors and 0 warnings.
Info:     Translation Complete.
Info:     Reading OPTISTRUCT from C:/Users/sihol/OneDrive/Desktop/ASE/MATLAB/RESULT FILES/ASE_Project2025_SuperPanel_3787415_redesign.fem using C:\Program Files\Altair\2023.1\hwdesktop\io\model_readers\feinput\bin\win64\optistruct.exe on 07-03-2025 01:06:38.
Info:     Processing Modules.
Info:     Processing Cards.
Info:     Processing System Collectors.
Info:     Processing Systems.
Info:     Processing Nodes.
Info:     Processing Vectorcols.
Info:     Processing Vectors.
Info:     Processing Materials.
Info:     Processing Properties.
Info:     Processing Components.
Info:     Processing Groups.
Info:     Processing Elements.
Info:     Processing Load Collectors.
Info:     Processing Equations.
Info:     Processing Loads.
Info:     Processing Assemblies.
Info:     Processing Curves.
Info:     Processing Blocks.
Info:     Processing Sets.
Info:     Processing Output Blocks.
Info:     Processing Load Steps.
Info:     Processing Sensors.
Info:     Processing Plys.
Info:     Processing Laminates.
Info:     Processing Designvars.
Info:     Processing Beamsectcols.
Info:     Processing Beamsections.
Info:     Processing Optitableentrs.
Info:     Processing Dequations.
Info:     Processing Optiresponses.
Info:     Processing Dvprels.
Info:     Processing Opticonstraints.
Info:     Processing Desvarlinks.
Info:     Processing Objectives.
Info:     Processing Opticontrols.
Info:     Processing Optidscreens.
Info:     Processing Tags.
Info:     Processing Dobjrefs.
Info:     Processing Contactsurfs.
Info:     Processing Shapes.
Info:     Processing Ddvals.
Info:     Processing Joints.
Info:     Processing Mechanismconstraints.
Info:     Processing Rigidwalls.
Info:     Processing Failures.
Info:     Processing Crosssections.
Info:     Processing Hourglass.
Info:     Processing Rigidbodies.
Info:     Processing Bodies.
Info:     Processing Mechanisms.
Info:     Processing Transformations.
Info:     Processing Positions.
Info:     Processing Outputrequests.
Info:     Processing Directmatrixinputs.
Info:     Processing Equivalences.
Info:     Processing Solvermasses.
Info:     Processing Analysisparameters.
Info:     Processing Parameters.

Summary:  Feinput finished with 0 errors and 0 warnings.
Info:     Translation Complete.
Info:     Reading OPTISTRUCT from C:/Users/sihol/OneDrive/Desktop/ASE/MATLAB/RESULT FILES/ASE_Project2025_SuperPanel_3787415_redesign.fem using C:\Program Files\Altair\2023.1\hwdesktop\io\model_readers\feinput\bin\win64\optistruct.exe on 07-03-2025 01:08:00.
Info:     Processing Modules.
Info:     Processing Cards.
Info:     Processing System Collectors.
Info:     Processing Systems.
Info:     Processing Nodes.
Info:     Processing Vectorcols.
Info:     Processing Vectors.
Info:     Processing Materials.
Info:     Processing Properties.
Info:     Processing Components.
Info:     Processing Groups.
Info:     Processing Elements.
Info:     Processing Load Collectors.
Info:     Processing Equations.
Info:     Processing Loads.
Info:     Processing Assemblies.
Info:     Processing Curves.
Info:     Processing Blocks.
Info:     Processing Sets.
Info:     Processing Output Blocks.
Info:     Processing Load Steps.
Info:     Processing Sensors.
Info:     Processing Plys.
Info:     Processing Laminates.
Info:     Processing Designvars.
Info:     Processing Beamsectcols.
Info:     Processing Beamsections.
Info:     Processing Optitableentrs.
Info:     Processing Dequations.
Info:     Processing Optiresponses.
Info:     Processing Dvprels.
Info:     Processing Opticonstraints.
Info:     Processing Desvarlinks.
Info:     Processing Objectives.
Info:     Processing Opticontrols.
Info:     Processing Optidscreens.
Info:     Processing Tags.
Info:     Processing Dobjrefs.
Info:     Processing Contactsurfs.
Info:     Processing Shapes.
Info:     Processing Ddvals.
Info:     Processing Joints.
Info:     Processing Mechanismconstraints.
Info:     Processing Rigidwalls.
Info:     Processing Failures.
Info:     Processing Crosssections.
Info:     Processing Hourglass.
Info:     Processing Rigidbodies.
Info:     Processing Bodies.
Info:     Processing Mechanisms.
Info:     Processing Transformations.
Info:     Processing Positions.
Info:     Processing Outputrequests.
Info:     Processing Directmatrixinputs.
Info:     Processing Equivalences.
Info:     Processing Solvermasses.
Info:     Processing Analysisparameters.
Info:     Processing Parameters.

Summary:  Feinput finished with 0 errors and 0 warnings.
Info:     Translation Complete.
Info:     Reading OPTISTRUCT from C:/Users/sihol/OneDrive/Desktop/ASE/MATLAB/RESULT FILES/ASE_Project2025_SuperPanel_3787415_redesign.fem using C:\Program Files\Altair\2023.1\hwdesktop\io\model_readers\feinput\bin\win64\optistruct.exe on 07-03-2025 01:19:26.
Info:     Processing Modules.
Info:     Processing Cards.
Info:     Processing System Collectors.
Info:     Processing Systems.
Info:     Processing Nodes.
Info:     Processing Vectorcols.
Info:     Processing Vectors.
Info:     Processing Materials.
Info:     Processing Properties.
Info:     Processing Components.
Info:     Processing Groups.
Info:     Processing Elements.
Info:     Processing Load Collectors.
Info:     Processing Equations.
Info:     Processing Loads.
Info:     Processing Assemblies.
Info:     Processing Curves.
Info:     Processing Blocks.
Info:     Processing Sets.
Info:     Processing Output Blocks.
Info:     Processing Load Steps.
Info:     Processing Sensors.
Info:     Processing Plys.
Info:     Processing Laminates.
Info:     Processing Designvars.
Info:     Processing Beamsectcols.
Info:     Processing Beamsections.
Info:     Processing Optitableentrs.
Info:     Processing Dequations.
Info:     Processing Optiresponses.
Info:     Processing Dvprels.
Info:     Processing Opticonstraints.
Info:     Processing Desvarlinks.
Info:     Processing Objectives.
Info:     Processing Opticontrols.
Info:     Processing Optidscreens.
Info:     Processing Tags.
Info:     Processing Dobjrefs.
Info:     Processing Contactsurfs.
Info:     Processing Shapes.
Info:     Processing Ddvals.
Info:     Processing Joints.
Info:     Processing Mechanismconstraints.
Info:     Processing Rigidwalls.
Info:     Processing Failures.
Info:     Processing Crosssections.
Info:     Processing Hourglass.
Info:     Processing Rigidbodies.
Info:     Processing Bodies.
Info:     Processing Mechanisms.
Info:     Processing Transformations.
Info:     Processing Positions.
Info:     Processing Outputrequests.
Info:     Processing Directmatrixinputs.
Info:     Processing Equivalences.
Info:     Processing Solvermasses.
Info:     Processing Analysisparameters.
Info:     Processing Parameters.

Summary:  Feinput finished with 0 errors and 0 warnings.
Info:     Translation Complete.
Info:     Reading OPTISTRUCT from C:/Users/sihol/OneDrive/Desktop/ASE/MATLAB/RESULT FILES/ASE_Project2025_SuperPanel_3787415_redesign.fem using C:\Program Files\Altair\2023.1\hwdesktop\io\model_readers\feinput\bin\win64\optistruct.exe on 07-03-2025 01:22:44.
Info:     Processing Modules.
Info:     Processing Cards.
Info:     Processing System Collectors.
Info:     Processing Systems.
Info:     Processing Nodes.
Info:     Processing Vectorcols.
Info:     Processing Vectors.
Info:     Processing Materials.
Info:     Processing Properties.
Info:     Processing Components.
Info:     Processing Groups.
Info:     Processing Elements.
Info:     Processing Load Collectors.
Info:     Processing Equations.
Info:     Processing Loads.
Info:     Processing Assemblies.
Info:     Processing Curves.
Info:     Processing Blocks.
Info:     Processing Sets.
Info:     Processing Output Blocks.
Info:     Processing Load Steps.
Info:     Processing Sensors.
Info:     Processing Plys.
Info:     Processing Laminates.
Info:     Processing Designvars.
Info:     Processing Beamsectcols.
Info:     Processing Beamsections.
Info:     Processing Optitableentrs.
Info:     Processing Dequations.
Info:     Processing Optiresponses.
Info:     Processing Dvprels.
Info:     Processing Opticonstraints.
Info:     Processing Desvarlinks.
Info:     Processing Objectives.
Info:     Processing Opticontrols.
Info:     Processing Optidscreens.
Info:     Processing Tags.
Info:     Processing Dobjrefs.
Info:     Processing Contactsurfs.
Info:     Processing Shapes.
Info:     Processing Ddvals.
Info:     Processing Joints.
Info:     Processing Mechanismconstraints.
Info:     Processing Rigidwalls.
Info:     Processing Failures.
Info:     Processing Crosssections.
Info:     Processing Hourglass.
Info:     Processing Rigidbodies.
Info:     Processing Bodies.
Info:     Processing Mechanisms.
Info:     Processing Transformations.
Info:     Processing Positions.
Info:     Processing Outputrequests.
Info:     Processing Directmatrixinputs.
Info:     Processing Equivalences.
Info:     Processing Solvermasses.
Info:     Processing Analysisparameters.
Info:     Processing Parameters.

Summary:  Feinput finished with 0 errors and 0 warnings.
Info:     Translation Complete.
Info:     Reading OPTISTRUCT from C:/Users/sihol/OneDrive/Desktop/ASE/MATLAB/RESULT FILES/ASE_Project2025_SuperPanel_3787415_redesign.fem using C:\Program Files\Altair\2023.1\hwdesktop\io\model_readers\feinput\bin\win64\optistruct.exe on 07-03-2025 01:25:19.
Info:     Processing Modules.
Info:     Processing Cards.
Info:     Processing System Collectors.
Info:     Processing Systems.
Info:     Processing Nodes.
Info:     Processing Vectorcols.
Info:     Processing Vectors.
Info:     Processing Materials.
Info:     Processing Properties.
Info:     Processing Components.
Info:     Processing Groups.
Info:     Processing Elements.
Info:     Processing Load Collectors.
Info:     Processing Equations.
Info:     Processing Loads.
Info:     Processing Assemblies.
Info:     Processing Curves.
Info:     Processing Blocks.
Info:     Processing Sets.
Info:     Processing Output Blocks.
Info:     Processing Load Steps.
Info:     Processing Sensors.
Info:     Processing Plys.
Info:     Processing Laminates.
Info:     Processing Designvars.
Info:     Processing Beamsectcols.
Info:     Processing Beamsections.
Info:     Processing Optitableentrs.
Info:     Processing Dequations.
Info:     Processing Optiresponses.
Info:     Processing Dvprels.
Info:     Processing Opticonstraints.
Info:     Processing Desvarlinks.
Info:     Processing Objectives.
Info:     Processing Opticontrols.
Info:     Processing Optidscreens.
Info:     Processing Tags.
Info:     Processing Dobjrefs.
Info:     Processing Contactsurfs.
Info:     Processing Shapes.
Info:     Processing Ddvals.
Info:     Processing Joints.
Info:     Processing Mechanismconstraints.
Info:     Processing Rigidwalls.
Info:     Processing Failures.
Info:     Processing Crosssections.
Info:     Processing Hourglass.
Info:     Processing Rigidbodies.
Info:     Processing Bodies.
Info:     Processing Mechanisms.
Info:     Processing Transformations.
Info:     Processing Positions.
Info:     Processing Outputrequests.
Info:     Processing Directmatrixinputs.
Info:     Processing Equivalences.
Info:     Processing Solvermasses.
Info:     Processing Analysisparameters.
Info:     Processing Parameters.

Summary:  Feinput finished with 0 errors and 0 warnings.
Info:     Translation Complete.
Info:     Reading OPTISTRUCT from C:/Users/sihol/OneDrive/Desktop/ASE/MATLAB/RESULT FILES/ASE_Project2025_SuperPanel_3787415_redesign.fem using C:\Program Files\Altair\2023.1\hwdesktop\io\model_readers\feinput\bin\win64\optistruct.exe on 07-03-2025 01:30:14.
Info:     Processing Modules.
Info:     Processing Cards.
Info:     Processing System Collectors.
Info:     Processing Systems.
Info:     Processing Nodes.
Info:     Processing Vectorcols.
Info:     Processing Vectors.
Info:     Processing Materials.
Info:     Processing Properties.
Info:     Processing Components.
Info:     Processing Groups.
Info:     Processing Elements.
Info:     Processing Load Collectors.
Info:     Processing Equations.
Info:     Processing Loads.
Info:     Processing Assemblies.
Info:     Processing Curves.
Info:     Processing Blocks.
Info:     Processing Sets.
Info:     Processing Output Blocks.
Info:     Processing Load Steps.
Info:     Processing Sensors.
Info:     Processing Plys.
Info:     Processing Laminates.
Info:     Processing Designvars.
Info:     Processing Beamsectcols.
Info:     Processing Beamsections.
Info:     Processing Optitableentrs.
Info:     Processing Dequations.
Info:     Processing Optiresponses.
Info:     Processing Dvprels.
Info:     Processing Opticonstraints.
Info:     Processing Desvarlinks.
Info:     Processing Objectives.
Info:     Processing Opticontrols.
Info:     Processing Optidscreens.
Info:     Processing Tags.
Info:     Processing Dobjrefs.
Info:     Processing Contactsurfs.
Info:     Processing Shapes.
Info:     Processing Ddvals.
Info:     Processing Joints.
Info:     Processing Mechanismconstraints.
Info:     Processing Rigidwalls.
Info:     Processing Failures.
Info:     Processing Crosssections.
Info:     Processing Hourglass.
Info:     Processing Rigidbodies.
Info:     Processing Bodies.
Info:     Processing Mechanisms.
Info:     Processing Transformations.
Info:     Processing Positions.
Info:     Processing Outputrequests.
Info:     Processing Directmatrixinputs.
Info:     Processing Equivalences.
Info:     Processing Solvermasses.
Info:     Processing Analysisparameters.
Info:     Processing Parameters.

Summary:  Feinput finished with 0 errors and 0 warnings.
Info:     Translation Complete.
Info:     Reading OPTISTRUCT from C:/Users/sihol/OneDrive/Desktop/ASE/MATLAB/RESULT FILES/ASE_Project2025_SuperPanel_3787415_redesign.fem using C:\Program Files\Altair\2023.1\hwdesktop\io\model_readers\feinput\bin\win64\optistruct.exe on 07-03-2025 01:31:39.
Info:     Processing Modules.
Info:     Processing Cards.
Info:     Processing System Collectors.
Info:     Processing Systems.
Info:     Processing Nodes.
Info:     Processing Vectorcols.
Info:     Processing Vectors.
Info:     Processing Materials.
Info:     Processing Properties.
Info:     Processing Components.
Info:     Processing Groups.
Info:     Processing Elements.
Info:     Processing Load Collectors.
Info:     Processing Equations.
Info:     Processing Loads.
Info:     Processing Assemblies.
Info:     Processing Curves.
Info:     Processing Blocks.
Info:     Processing Sets.
Info:     Processing Output Blocks.
Info:     Processing Load Steps.
Info:     Processing Sensors.
Info:     Processing Plys.
Info:     Processing Laminates.
Info:     Processing Designvars.
Info:     Processing Beamsectcols.
Info:     Processing Beamsections.
Info:     Processing Optitableentrs.
Info:     Processing Dequations.
Info:     Processing Optiresponses.
Info:     Processing Dvprels.
Info:     Processing Opticonstraints.
Info:     Processing Desvarlinks.
Info:     Processing Objectives.
Info:     Processing Opticontrols.
Info:     Processing Optidscreens.
Info:     Processing Tags.
Info:     Processing Dobjrefs.
Info:     Processing Contactsurfs.
Info:     Processing Shapes.
Info:     Processing Ddvals.
Info:     Processing Joints.
Info:     Processing Mechanismconstraints.
Info:     Processing Rigidwalls.
Info:     Processing Failures.
Info:     Processing Crosssections.
Info:     Processing Hourglass.
Info:     Processing Rigidbodies.
Info:     Processing Bodies.
Info:     Processing Mechanisms.
Info:     Processing Transformations.
Info:     Processing Positions.
Info:     Processing Outputrequests.
Info:     Processing Directmatrixinputs.
Info:     Processing Equivalences.
Info:     Processing Solvermasses.
Info:     Processing Analysisparameters.
Info:     Processing Parameters.

Summary:  Feinput finished with 0 errors and 0 warnings.
Info:     Translation Complete.
Info:     Reading OPTISTRUCT from C:/Users/sihol/OneDrive/Desktop/ASE/MATLAB/RESULT FILES/ASE_Project2025_SuperPanel_3787415_redesign.fem using C:\Program Files\Altair\2023.1\hwdesktop\io\model_readers\feinput\bin\win64\optistruct.exe on 07-03-2025 01:37:07.
Info:     Processing Modules.
Info:     Processing Cards.
Info:     Processing System Collectors.
Info:     Processing Systems.
Info:     Processing Nodes.
Info:     Processing Vectorcols.
Info:     Processing Vectors.
Info:     Processing Materials.
Info:     Processing Properties.
Info:     Processing Components.
Info:     Processing Groups.
Info:     Processing Elements.
Info:     Processing Load Collectors.
Info:     Processing Equations.
Info:     Processing Loads.
Info:     Processing Assemblies.
Info:     Processing Curves.
Info:     Processing Blocks.
Info:     Processing Sets.
Info:     Processing Output Blocks.
Info:     Processing Load Steps.
Info:     Processing Sensors.
Info:     Processing Plys.
Info:     Processing Laminates.
Info:     Processing Designvars.
Info:     Processing Beamsectcols.
Info:     Processing Beamsections.
Info:     Processing Optitableentrs.
Info:     Processing Dequations.
Info:     Processing Optiresponses.
Info:     Processing Dvprels.
Info:     Processing Opticonstraints.
Info:     Processing Desvarlinks.
Info:     Processing Objectives.
Info:     Processing Opticontrols.
Info:     Processing Optidscreens.
Info:     Processing Tags.
Info:     Processing Dobjrefs.
Info:     Processing Contactsurfs.
Info:     Processing Shapes.
Info:     Processing Ddvals.
Info:     Processing Joints.
Info:     Processing Mechanismconstraints.
Info:     Processing Rigidwalls.
Info:     Processing Failures.
Info:     Processing Crosssections.
Info:     Processing Hourglass.
Info:     Processing Rigidbodies.
Info:     Processing Bodies.
Info:     Processing Mechanisms.
Info:     Processing Transformations.
Info:     Processing Positions.
Info:     Processing Outputrequests.
Info:     Processing Directmatrixinputs.
Info:     Processing Equivalences.
Info:     Processing Solvermasses.
Info:     Processing Analysisparameters.
Info:     Processing Parameters.

Summary:  Feinput finished with 0 errors and 0 warnings.
Info:     Translation Complete.
Info:     Reading OPTISTRUCT from C:/Users/sihol/OneDrive/Desktop/ASE/MATLAB/RESULT FILES/ASE_Project2025_SuperPanel_3787415_redesign.fem using C:\Program Files\Altair\2023.1\hwdesktop\io\model_readers\feinput\bin\win64\optistruct.exe on 07-03-2025 01:44:20.
Info:     Processing Modules.
Info:     Processing Cards.
Info:     Processing System Collectors.
Info:     Processing Systems.
Info:     Processing Nodes.
Info:     Processing Vectorcols.
Info:     Processing Vectors.
Info:     Processing Materials.
Info:     Processing Properties.
Info:     Processing Components.
Info:     Processing Groups.
Info:     Processing Elements.
Info:     Processing Load Collectors.
Info:     Processing Equations.
Info:     Processing Loads.
Info:     Processing Assemblies.
Info:     Processing Curves.
Info:     Processing Blocks.
Info:     Processing Sets.
Info:     Processing Output Blocks.
Info:     Processing Load Steps.
Info:     Processing Sensors.
Info:     Processing Plys.
Info:     Processing Laminates.
Info:     Processing Designvars.
Info:     Processing Beamsectcols.
Info:     Processing Beamsections.
Info:     Processing Optitableentrs.
Info:     Processing Dequations.
Info:     Processing Optiresponses.
Info:     Processing Dvprels.
Info:     Processing Opticonstraints.
Info:     Processing Desvarlinks.
Info:     Processing Objectives.
Info:     Processing Opticontrols.
Info:     Processing Optidscreens.
Info:     Processing Tags.
Info:     Processing Dobjrefs.
Info:     Processing Contactsurfs.
Info:     Processing Shapes.
Info:     Processing Ddvals.
Info:     Processing Joints.
Info:     Processing Mechanismconstraints.
Info:     Processing Rigidwalls.
Info:     Processing Failures.
Info:     Processing Crosssections.
Info:     Processing Hourglass.
Info:     Processing Rigidbodies.
Info:     Processing Bodies.
Info:     Processing Mechanisms.
Info:     Processing Transformations.
Info:     Processing Positions.
Info:     Processing Outputrequests.
Info:     Processing Directmatrixinputs.
Info:     Processing Equivalences.
Info:     Processing Solvermasses.
Info:     Processing Analysisparameters.
Info:     Processing Parameters.

Summary:  Feinput finished with 0 errors and 0 warnings.
Info:     Translation Complete.
Info:     Reading OPTISTRUCT from C:/Users/sihol/OneDrive/Desktop/ASE/MATLAB/RESULT FILES/ASE_Project2025_SuperPanel_3787415_redesign.fem using C:\Program Files\Altair\2023.1\hwdesktop\io\model_readers\feinput\bin\win64\optistruct.exe on 07-03-2025 01:53:14.
Info:     Processing Modules.
Info:     Processing Cards.
Info:     Processing System Collectors.
Info:     Processing Systems.
Info:     Processing Nodes.
Info:     Processing Vectorcols.
Info:     Processing Vectors.
Info:     Processing Materials.
Info:     Processing Properties.
Info:     Processing Components.
Info:     Processing Groups.
Info:     Processing Elements.
Info:     Processing Load Collectors.
Info:     Processing Equations.
Info:     Processing Loads.
Info:     Processing Assemblies.
Info:     Processing Curves.
Info:     Processing Blocks.
Info:     Processing Sets.
Info:     Processing Output Blocks.
Info:     Processing Load Steps.
Info:     Processing Sensors.
Info:     Processing Plys.
Info:     Processing Laminates.
Info:     Processing Designvars.
Info:     Processing Beamsectcols.
Info:     Processing Beamsections.
Info:     Processing Optitableentrs.
Info:     Processing Dequations.
Info:     Processing Optiresponses.
Info:     Processing Dvprels.
Info:     Processing Opticonstraints.
Info:     Processing Desvarlinks.
Info:     Processing Objectives.
Info:     Processing Opticontrols.
Info:     Processing Optidscreens.
Info:     Processing Tags.
Info:     Processing Dobjrefs.
Info:     Processing Contactsurfs.
Info:     Processing Shapes.
Info:     Processing Ddvals.
Info:     Processing Joints.
Info:     Processing Mechanismconstraints.
Info:     Processing Rigidwalls.
Info:     Processing Failures.
Info:     Processing Crosssections.
Info:     Processing Hourglass.
Info:     Processing Rigidbodies.
Info:     Processing Bodies.
Info:     Processing Mechanisms.
Info:     Processing Transformations.
Info:     Processing Positions.
Info:     Processing Outputrequests.
Info:     Processing Directmatrixinputs.
Info:     Processing Equivalences.
Info:     Processing Solvermasses.
Info:     Processing Analysisparameters.
Info:     Processing Parameters.

Summary:  Feinput finished with 0 errors and 0 warnings.
Info:     Translation Complete.
Info:     Reading OPTISTRUCT from C:/Users/sihol/OneDrive/Desktop/ASE/MATLAB/RESULT FILES/ASE_Project2025_SuperPanel_3787415_redesign.fem using C:\Program Files\Altair\2023.1\hwdesktop\io\model_readers\feinput\bin\win64\optistruct.exe on 07-03-2025 01:59:36.
Info:     Processing Modules.
Info:     Processing Cards.
Info:     Processing System Collectors.
Info:     Processing Systems.
Info:     Processing Nodes.
Info:     Processing Vectorcols.
Info:     Processing Vectors.
Info:     Processing Materials.
Info:     Processing Properties.
Info:     Processing Components.
Info:     Processing Groups.
Info:     Processing Elements.
Info:     Processing Load Collectors.
Info:     Processing Equations.
Info:     Processing Loads.
Info:     Processing Assemblies.
Info:     Processing Curves.
Info:     Processing Blocks.
Info:     Processing Sets.
Info:     Processing Output Blocks.
Info:     Processing Load Steps.
Info:     Processing Sensors.
Info:     Processing Plys.
Info:     Processing Laminates.
Info:     Processing Designvars.
Info:     Processing Beamsectcols.
Info:     Processing Beamsections.
Info:     Processing Optitableentrs.
Info:     Processing Dequations.
Info:     Processing Optiresponses.
Info:     Processing Dvprels.
Info:     Processing Opticonstraints.
Info:     Processing Desvarlinks.
Info:     Processing Objectives.
Info:     Processing Opticontrols.
Info:     Processing Optidscreens.
Info:     Processing Tags.
Info:     Processing Dobjrefs.
Info:     Processing Contactsurfs.
Info:     Processing Shapes.
Info:     Processing Ddvals.
Info:     Processing Joints.
Info:     Processing Mechanismconstraints.
Info:     Processing Rigidwalls.
Info:     Processing Failures.
Info:     Processing Crosssections.
Info:     Processing Hourglass.
Info:     Processing Rigidbodies.
Info:     Processing Bodies.
Info:     Processing Mechanisms.
Info:     Processing Transformations.
Info:     Processing Positions.
Info:     Processing Outputrequests.
Info:     Processing Directmatrixinputs.
Info:     Processing Equivalences.
Info:     Processing Solvermasses.
Info:     Processing Analysisparameters.
Info:     Processing Parameters.

Summary:  Feinput finished with 0 errors and 0 warnings.
Info:     Translation Complete.
Info:     Reading OPTISTRUCT from C:/Users/sihol/OneDrive/Desktop/ASE/MATLAB/RESULT FILES/ASE_Project2025_SuperPanel_3787415_redesign.fem using C:\Program Files\Altair\2023.1\hwdesktop\io\model_readers\feinput\bin\win64\optistruct.exe on 07-03-2025 02:00:37.
Info:     Processing Modules.
Info:     Processing Cards.
Info:     Processing System Collectors.
Info:     Processing Systems.
Info:     Processing Nodes.
Info:     Processing Vectorcols.
Info:     Processing Vectors.
Info:     Processing Materials.
Info:     Processing Properties.
Info:     Processing Components.
Info:     Processing Groups.
Info:     Processing Elements.
Info:     Processing Load Collectors.
Info:     Processing Equations.
Info:     Processing Loads.
Info:     Processing Assemblies.
Info:     Processing Curves.
Info:     Processing Blocks.
Info:     Processing Sets.
Info:     Processing Output Blocks.
Info:     Processing Load Steps.
Info:     Processing Sensors.
Info:     Processing Plys.
Info:     Processing Laminates.
Info:     Processing Designvars.
Info:     Processing Beamsectcols.
Info:     Processing Beamsections.
Info:     Processing Optitableentrs.
Info:     Processing Dequations.
Info:     Processing Optiresponses.
Info:     Processing Dvprels.
Info:     Processing Opticonstraints.
Info:     Processing Desvarlinks.
Info:     Processing Objectives.
Info:     Processing Opticontrols.
Info:     Processing Optidscreens.
Info:     Processing Tags.
Info:     Processing Dobjrefs.
Info:     Processing Contactsurfs.
Info:     Processing Shapes.
Info:     Processing Ddvals.
Info:     Processing Joints.
Info:     Processing Mechanismconstraints.
Info:     Processing Rigidwalls.
Info:     Processing Failures.
Info:     Processing Crosssections.
Info:     Processing Hourglass.
Info:     Processing Rigidbodies.
Info:     Processing Bodies.
Info:     Processing Mechanisms.
Info:     Processing Transformations.
Info:     Processing Positions.
Info:     Processing Outputrequests.
Info:     Processing Directmatrixinputs.
Info:     Processing Equivalences.
Info:     Processing Solvermasses.
Info:     Processing Analysisparameters.
Info:     Processing Parameters.

Summary:  Feinput finished with 0 errors and 0 warnings.
Info:     Translation Complete.
Info:     Reading OPTISTRUCT from C:/Users/sihol/OneDrive/Desktop/ASE/MATLAB/RESULT FILES/ASE_Project2025_SuperPanel_3641389_redesign.fem using C:\Program Files\Altair\2023.1\hwdesktop\io\model_readers\feinput\bin\win64\optistruct.exe on 07-03-2025 02:05:12.
Info:     Processing Modules.
Info:     Processing Cards.
Info:     Processing System Collectors.
Info:     Processing Systems.
Info:     Processing Nodes.
Info:     Processing Vectorcols.
Info:     Processing Vectors.
Info:     Processing Materials.
Info:     Processing Properties.
Info:     Processing Components.
Info:     Processing Groups.
Info:     Processing Elements.
Info:     Processing Load Collectors.
Info:     Processing Equations.
Info:     Processing Loads.
Info:     Processing Assemblies.
Info:     Processing Curves.
Info:     Processing Blocks.
Info:     Processing Sets.
Info:     Processing Output Blocks.
Info:     Processing Load Steps.
Info:     Processing Sensors.
Info:     Processing Plys.
Info:     Processing Laminates.
Info:     Processing Designvars.
Info:     Processing Beamsectcols.
Info:     Processing Beamsections.
Info:     Processing Optitableentrs.
Info:     Processing Dequations.
Info:     Processing Optiresponses.
Info:     Processing Dvprels.
Info:     Processing Opticonstraints.
Info:     Processing Desvarlinks.
Info:     Processing Objectives.
Info:     Processing Opticontrols.
Info:     Processing Optidscreens.
Info:     Processing Tags.
Info:     Processing Dobjrefs.
Info:     Processing Contactsurfs.
Info:     Processing Shapes.
Info:     Processing Ddvals.
Info:     Processing Joints.
Info:     Processing Mechanismconstraints.
Info:     Processing Rigidwalls.
Info:     Processing Failures.
Info:     Processing Crosssections.
Info:     Processing Hourglass.
Info:     Processing Rigidbodies.
Info:     Processing Bodies.
Info:     Processing Mechanisms.
Info:     Processing Transformations.
Info:     Processing Positions.
Info:     Processing Outputrequests.
Info:     Processing Directmatrixinputs.
Info:     Processing Equivalences.
Info:     Processing Solvermasses.
Info:     Processing Analysisparameters.
Info:     Processing Parameters.

Summary:  Feinput finished with 0 errors and 0 warnings.
Info:     Translation Complete.
Info:     Reading OPTISTRUCT from C:/Users/sihol/OneDrive/Desktop/ASE/MATLAB/RESULT FILES/ASE_Project2025_SuperPanel_3641389_redesign.fem using C:\Program Files\Altair\2023.1\hwdesktop\io\model_readers\feinput\bin\win64\optistruct.exe on 07-03-2025 02:08:07.
Info:     Processing Modules.
Info:     Processing Cards.
Info:     Processing System Collectors.
Info:     Processing Systems.
Info:     Processing Nodes.
Info:     Processing Vectorcols.
Info:     Processing Vectors.
Info:     Processing Materials.
Info:     Processing Properties.
Info:     Processing Components.
Info:     Processing Groups.
Info:     Processing Elements.
Info:     Processing Load Collectors.
Info:     Processing Equations.
Info:     Processing Loads.
Info:     Processing Assemblies.
Info:     Processing Curves.
Info:     Processing Blocks.
Info:     Processing Sets.
Info:     Processing Output Blocks.
Info:     Processing Load Steps.
Info:     Processing Sensors.
Info:     Processing Plys.
Info:     Processing Laminates.
Info:     Processing Designvars.
Info:     Processing Beamsectcols.
Info:     Processing Beamsections.
Info:     Processing Optitableentrs.
Info:     Processing Dequations.
Info:     Processing Optiresponses.
Info:     Processing Dvprels.
Info:     Processing Opticonstraints.
Info:     Processing Desvarlinks.
Info:     Processing Objectives.
Info:     Processing Opticontrols.
Info:     Processing Optidscreens.
Info:     Processing Tags.
Info:     Processing Dobjrefs.
Info:     Processing Contactsurfs.
Info:     Processing Shapes.
Info:     Processing Ddvals.
Info:     Processing Joints.
Info:     Processing Mechanismconstraints.
Info:     Processing Rigidwalls.
Info:     Processing Failures.
Info:     Processing Crosssections.
Info:     Processing Hourglass.
Info:     Processing Rigidbodies.
Info:     Processing Bodies.
Info:     Processing Mechanisms.
Info:     Processing Transformations.
Info:     Processing Positions.
Info:     Processing Outputrequests.
Info:     Processing Directmatrixinputs.
Info:     Processing Equivalences.
Info:     Processing Solvermasses.
Info:     Processing Analysisparameters.
Info:     Processing Parameters.

Summary:  Feinput finished with 0 errors and 0 warnings.
Info:     Translation Complete.
Info:     Reading OPTISTRUCT from C:/Users/sihol/OneDrive/Desktop/ASE/MATLAB/RESULT FILES/ASE_Project2025_SuperPanel_3787415_redesign.fem using C:\Program Files\Altair\2023.1\hwdesktop\io\model_readers\feinput\bin\win64\optistruct.exe on 07-03-2025 02:11:39.
Info:     Processing Modules.
Info:     Processing Cards.
Info:     Processing System Collectors.
Info:     Processing Systems.
Info:     Processing Nodes.
Info:     Processing Vectorcols.
Info:     Processing Vectors.
Info:     Processing Materials.
Info:     Processing Properties.
Info:     Processing Components.
Info:     Processing Groups.
Info:     Processing Elements.
Info:     Processing Load Collectors.
Info:     Processing Equations.
Info:     Processing Loads.
Info:     Processing Assemblies.
Info:     Processing Curves.
Info:     Processing Blocks.
Info:     Processing Sets.
Info:     Processing Output Blocks.
Info:     Processing Load Steps.
Info:     Processing Sensors.
Info:     Processing Plys.
Info:     Processing Laminates.
Info:     Processing Designvars.
Info:     Processing Beamsectcols.
Info:     Processing Beamsections.
Info:     Processing Optitableentrs.
Info:     Processing Dequations.
Info:     Processing Optiresponses.
Info:     Processing Dvprels.
Info:     Processing Opticonstraints.
Info:     Processing Desvarlinks.
Info:     Processing Objectives.
Info:     Processing Opticontrols.
Info:     Processing Optidscreens.
Info:     Processing Tags.
Info:     Processing Dobjrefs.
Info:     Processing Contactsurfs.
Info:     Processing Shapes.
Info:     Processing Ddvals.
Info:     Processing Joints.
Info:     Processing Mechanismconstraints.
Info:     Processing Rigidwalls.
Info:     Processing Failures.
Info:     Processing Crosssections.
Info:     Processing Hourglass.
Info:     Processing Rigidbodies.
Info:     Processing Bodies.
Info:     Processing Mechanisms.
Info:     Processing Transformations.
Info:     Processing Positions.
Info:     Processing Outputrequests.
Info:     Processing Directmatrixinputs.
Info:     Processing Equivalences.
Info:     Processing Solvermasses.
Info:     Processing Analysisparameters.
Info:     Processing Parameters.

Summary:  Feinput finished with 0 errors and 0 warnings.
Info:     Translation Complete.
Info:     Reading OPTISTRUCT from C:/Users/sihol/OneDrive/Desktop/ASE/MATLAB/RESULT FILES/ASE_Project2025_SuperPanel_3787415_redesign.fem using C:\Program Files\Altair\2023.1\hwdesktop\io\model_readers\feinput\bin\win64\optistruct.exe on 07-03-2025 02:12:29.
Info:     Processing Modules.
Info:     Processing Cards.
Info:     Processing System Collectors.
Info:     Processing Systems.
Info:     Processing Nodes.
Info:     Processing Vectorcols.
Info:     Processing Vectors.
Info:     Processing Materials.
Info:     Processing Properties.
Info:     Processing Components.
Info:     Processing Groups.
Info:     Processing Elements.
Info:     Processing Load Collectors.
Info:     Processing Equations.
Info:     Processing Loads.
Info:     Processing Assemblies.
Info:     Processing Curves.
Info:     Processing Blocks.
Info:     Processing Sets.
Info:     Processing Output Blocks.
Info:     Processing Load Steps.
Info:     Processing Sensors.
Info:     Processing Plys.
Info:     Processing Laminates.
Info:     Processing Designvars.
Info:     Processing Beamsectcols.
Info:     Processing Beamsections.
Info:     Processing Optitableentrs.
Info:     Processing Dequations.
Info:     Processing Optiresponses.
Info:     Processing Dvprels.
Info:     Processing Opticonstraints.
Info:     Processing Desvarlinks.
Info:     Processing Objectives.
Info:     Processing Opticontrols.
Info:     Processing Optidscreens.
Info:     Processing Tags.
Info:     Processing Dobjrefs.
Info:     Processing Contactsurfs.
Info:     Processing Shapes.
Info:     Processing Ddvals.
Info:     Processing Joints.
Info:     Processing Mechanismconstraints.
Info:     Processing Rigidwalls.
Info:     Processing Failures.
Info:     Processing Crosssections.
Info:     Processing Hourglass.
Info:     Processing Rigidbodies.
Info:     Processing Bodies.
Info:     Processing Mechanisms.
Info:     Processing Transformations.
Info:     Processing Positions.
Info:     Processing Outputrequests.
Info:     Processing Directmatrixinputs.
Info:     Processing Equivalences.
Info:     Processing Solvermasses.
Info:     Processing Analysisparameters.
Info:     Processing Parameters.

Summary:  Feinput finished with 0 errors and 0 warnings.
Info:     Translation Complete.
Info:     Reading OPTISTRUCT from C:/Users/sihol/OneDrive/Desktop/ASE/MATLAB/RESULT FILES/ASE_Project2025_SuperPanel_3787415_redesign.fem using C:\Program Files\Altair\2023.1\hwdesktop\io\model_readers\feinput\bin\win64\optistruct.exe on 07-03-2025 02:15:07.
Info:     Processing Modules.
Info:     Processing Cards.
Info:     Processing System Collectors.
Info:     Processing Systems.
Info:     Processing Nodes.
Info:     Processing Vectorcols.
Info:     Processing Vectors.
Info:     Processing Materials.
Info:     Processing Properties.
Info:     Processing Components.
Info:     Processing Groups.
Info:     Processing Elements.
Info:     Processing Load Collectors.
Info:     Processing Equations.
Info:     Processing Loads.
Info:     Processing Assemblies.
Info:     Processing Curves.
Info:     Processing Blocks.
Info:     Processing Sets.
Info:     Processing Output Blocks.
Info:     Processing Load Steps.
Info:     Processing Sensors.
Info:     Processing Plys.
Info:     Processing Laminates.
Info:     Processing Designvars.
Info:     Processing Beamsectcols.
Info:     Processing Beamsections.
Info:     Processing Optitableentrs.
Info:     Processing Dequations.
Info:     Processing Optiresponses.
Info:     Processing Dvprels.
Info:     Processing Opticonstraints.
Info:     Processing Desvarlinks.
Info:     Processing Objectives.
Info:     Processing Opticontrols.
Info:     Processing Optidscreens.
Info:     Processing Tags.
Info:     Processing Dobjrefs.
Info:     Processing Contactsurfs.
Info:     Processing Shapes.
Info:     Processing Ddvals.
Info:     Processing Joints.
Info:     Processing Mechanismconstraints.
Info:     Processing Rigidwalls.
Info:     Processing Failures.
Info:     Processing Crosssections.
Info:     Processing Hourglass.
Info:     Processing Rigidbodies.
Info:     Processing Bodies.
Info:     Processing Mechanisms.
Info:     Processing Transformations.
Info:     Processing Positions.
Info:     Processing Outputrequests.
Info:     Processing Directmatrixinputs.
Info:     Processing Equivalences.
Info:     Processing Solvermasses.
Info:     Processing Analysisparameters.
Info:     Processing Parameters.

Summary:  Feinput finished with 0 errors and 0 warnings.
Info:     Translation Complete.
Info:     Reading OPTISTRUCT from C:/Users/sihol/OneDrive/Desktop/ASE/MATLAB/RESULT FILES/ASE_Project2025_SuperPanel_3787415_redesign.fem using C:\Program Files\Altair\2023.1\hwdesktop\io\model_readers\feinput\bin\win64\optistruct.exe on 07-03-2025 02:16:18.
Info:     Processing Modules.
Info:     Processing Cards.
Info:     Processing System Collectors.
Info:     Processing Systems.
Info:     Processing Nodes.
Info:     Processing Vectorcols.
Info:     Processing Vectors.
Info:     Processing Materials.
Info:     Processing Properties.
Info:     Processing Components.
Info:     Processing Groups.
Info:     Processing Elements.
Info:     Processing Load Collectors.
Info:     Processing Equations.
Info:     Processing Loads.
Info:     Processing Assemblies.
Info:     Processing Curves.
Info:     Processing Blocks.
Info:     Processing Sets.
Info:     Processing Output Blocks.
Info:     Processing Load Steps.
Info:     Processing Sensors.
Info:     Processing Plys.
Info:     Processing Laminates.
Info:     Processing Designvars.
Info:     Processing Beamsectcols.
Info:     Processing Beamsections.
Info:     Processing Optitableentrs.
Info:     Processing Dequations.
Info:     Processing Optiresponses.
Info:     Processing Dvprels.
Info:     Processing Opticonstraints.
Info:     Processing Desvarlinks.
Info:     Processing Objectives.
Info:     Processing Opticontrols.
Info:     Processing Optidscreens.
Info:     Processing Tags.
Info:     Processing Dobjrefs.
Info:     Processing Contactsurfs.
Info:     Processing Shapes.
Info:     Processing Ddvals.
Info:     Processing Joints.
Info:     Processing Mechanismconstraints.
Info:     Processing Rigidwalls.
Info:     Processing Failures.
Info:     Processing Crosssections.
Info:     Processing Hourglass.
Info:     Processing Rigidbodies.
Info:     Processing Bodies.
Info:     Processing Mechanisms.
Info:     Processing Transformations.
Info:     Processing Positions.
Info:     Processing Outputrequests.
Info:     Processing Directmatrixinputs.
Info:     Processing Equivalences.
Info:     Processing Solvermasses.
Info:     Processing Analysisparameters.
Info:     Processing Parameters.

Summary:  Feinput finished with 0 errors and 0 warnings.
Info:     Translation Complete.
Info:     Reading OPTISTRUCT from C:/Users/sihol/OneDrive/Desktop/ASE/MATLAB/RESULT FILES/ASE_Project2025_SuperPanel_3787415_redesign.fem using C:\Program Files\Altair\2023.1\hwdesktop\io\model_readers\feinput\bin\win64\optistruct.exe on 07-03-2025 02:26:33.
Info:     Processing Modules.
Info:     Processing Cards.
Info:     Processing System Collectors.
Info:     Processing Systems.
Info:     Processing Nodes.
Info:     Processing Vectorcols.
Info:     Processing Vectors.
Info:     Processing Materials.
Info:     Processing Properties.
Info:     Processing Components.
Info:     Processing Groups.
Info:     Processing Elements.
Info:     Processing Load Collectors.
Info:     Processing Equations.
Info:     Processing Loads.
Info:     Processing Assemblies.
Info:     Processing Curves.
Info:     Processing Blocks.
Info:     Processing Sets.
Info:     Processing Output Blocks.
Info:     Processing Load Steps.
Info:     Processing Sensors.
Info:     Processing Plys.
Info:     Processing Laminates.
Info:     Processing Designvars.
Info:     Processing Beamsectcols.
Info:     Processing Beamsections.
Info:     Processing Optitableentrs.
Info:     Processing Dequations.
Info:     Processing Optiresponses.
Info:     Processing Dvprels.
Info:     Processing Opticonstraints.
Info:     Processing Desvarlinks.
Info:     Processing Objectives.
Info:     Processing Opticontrols.
Info:     Processing Optidscreens.
Info:     Processing Tags.
Info:     Processing Dobjrefs.
Info:     Processing Contactsurfs.
Info:     Processing Shapes.
Info:     Processing Ddvals.
Info:     Processing Joints.
Info:     Processing Mechanismconstraints.
Info:     Processing Rigidwalls.
Info:     Processing Failures.
Info:     Processing Crosssections.
Info:     Processing Hourglass.
Info:     Processing Rigidbodies.
Info:     Processing Bodies.
Info:     Processing Mechanisms.
Info:     Processing Transformations.
Info:     Processing Positions.
Info:     Processing Outputrequests.
Info:     Processing Directmatrixinputs.
Info:     Processing Equivalences.
Info:     Processing Solvermasses.
Info:     Processing Analysisparameters.
Info:     Processing Parameters.

Summary:  Feinput finished with 0 errors and 0 warnings.
Info:     Translation Complete.
Info:     Reading OPTISTRUCT from C:/Users/sihol/OneDrive/Desktop/ASE/MATLAB/RESULT FILES/ASE_Project2025_SuperPanel_3787415_redesign.fem using C:\Program Files\Altair\2023.1\hwdesktop\io\model_readers\feinput\bin\win64\optistruct.exe on 07-03-2025 02:27:45.
Info:     Processing Modules.
Info:     Processing Cards.
Info:     Processing System Collectors.
Info:     Processing Systems.
Info:     Processing Nodes.
Info:     Processing Vectorcols.
Info:     Processing Vectors.
Info:     Processing Materials.
Info:     Processing Properties.
Info:     Processing Components.
Info:     Processing Groups.
Info:     Processing Elements.
Info:     Processing Load Collectors.
Info:     Processing Equations.
Info:     Processing Loads.
Info:     Processing Assemblies.
Info:     Processing Curves.
Info:     Processing Blocks.
Info:     Processing Sets.
Info:     Processing Output Blocks.
Info:     Processing Load Steps.
Info:     Processing Sensors.
Info:     Processing Plys.
Info:     Processing Laminates.
Info:     Processing Designvars.
Info:     Processing Beamsectcols.
Info:     Processing Beamsections.
Info:     Processing Optitableentrs.
Info:     Processing Dequations.
Info:     Processing Optiresponses.
Info:     Processing Dvprels.
Info:     Processing Opticonstraints.
Info:     Processing Desvarlinks.
Info:     Processing Objectives.
Info:     Processing Opticontrols.
Info:     Processing Optidscreens.
Info:     Processing Tags.
Info:     Processing Dobjrefs.
Info:     Processing Contactsurfs.
Info:     Processing Shapes.
Info:     Processing Ddvals.
Info:     Processing Joints.
Info:     Processing Mechanismconstraints.
Info:     Processing Rigidwalls.
Info:     Processing Failures.
Info:     Processing Crosssections.
Info:     Processing Hourglass.
Info:     Processing Rigidbodies.
Info:     Processing Bodies.
Info:     Processing Mechanisms.
Info:     Processing Transformations.
Info:     Processing Positions.
Info:     Processing Outputrequests.
Info:     Processing Directmatrixinputs.
Info:     Processing Equivalences.
Info:     Processing Solvermasses.
Info:     Processing Analysisparameters.
Info:     Processing Parameters.

Summary:  Feinput finished with 0 errors and 0 warnings.
Info:     Translation Complete.
Info:     Reading OPTISTRUCT from C:/Users/sihol/OneDrive/Desktop/ASE/MATLAB/RESULT FILES/ASE_Project2025_SuperPanel_3787415_redesign.fem using C:\Program Files\Altair\2023.1\hwdesktop\io\model_readers\feinput\bin\win64\optistruct.exe on 07-03-2025 02:31:16.
Info:     Processing Modules.
Info:     Processing Cards.
Info:     Processing System Collectors.
Info:     Processing Systems.
Info:     Processing Nodes.
Info:     Processing Vectorcols.
Info:     Processing Vectors.
Info:     Processing Materials.
Info:     Processing Properties.
Info:     Processing Components.
Info:     Processing Groups.
Info:     Processing Elements.
Info:     Processing Load Collectors.
Info:     Processing Equations.
Info:     Processing Loads.
Info:     Processing Assemblies.
Info:     Processing Curves.
Info:     Processing Blocks.
Info:     Processing Sets.
Info:     Processing Output Blocks.
Info:     Processing Load Steps.
Info:     Processing Sensors.
Info:     Processing Plys.
Info:     Processing Laminates.
Info:     Processing Designvars.
Info:     Processing Beamsectcols.
Info:     Processing Beamsections.
Info:     Processing Optitableentrs.
Info:     Processing Dequations.
Info:     Processing Optiresponses.
Info:     Processing Dvprels.
Info:     Processing Opticonstraints.
Info:     Processing Desvarlinks.
Info:     Processing Objectives.
Info:     Processing Opticontrols.
Info:     Processing Optidscreens.
Info:     Processing Tags.
Info:     Processing Dobjrefs.
Info:     Processing Contactsurfs.
Info:     Processing Shapes.
Info:     Processing Ddvals.
Info:     Processing Joints.
Info:     Processing Mechanismconstraints.
Info:     Processing Rigidwalls.
Info:     Processing Failures.
Info:     Processing Crosssections.
Info:     Processing Hourglass.
Info:     Processing Rigidbodies.
Info:     Processing Bodies.
Info:     Processing Mechanisms.
Info:     Processing Transformations.
Info:     Processing Positions.
Info:     Processing Outputrequests.
Info:     Processing Directmatrixinputs.
Info:     Processing Equivalences.
Info:     Processing Solvermasses.
Info:     Processing Analysisparameters.
Info:     Processing Parameters.

Summary:  Feinput finished with 0 errors and 0 warnings.
Info:     Translation Complete.
Info:     Reading OPTISTRUCT from C:/Users/sihol/OneDrive/Desktop/ASE/MATLAB/RESULT FILES/ASE_Project2025_SuperPanel_3787415_redesign.fem using C:\Program Files\Altair\2023.1\hwdesktop\io\model_readers\feinput\bin\win64\optistruct.exe on 07-03-2025 02:34:26.
Info:     Processing Modules.
Info:     Processing Cards.
Info:     Processing System Collectors.
Info:     Processing Systems.
Info:     Processing Nodes.
Info:     Processing Vectorcols.
Info:     Processing Vectors.
Info:     Processing Materials.
Info:     Processing Properties.
Info:     Processing Components.
Info:     Processing Groups.
Info:     Processing Elements.
Info:     Processing Load Collectors.
Info:     Processing Equations.
Info:     Processing Loads.
Info:     Processing Assemblies.
Info:     Processing Curves.
Info:     Processing Blocks.
Info:     Processing Sets.
Info:     Processing Output Blocks.
Info:     Processing Load Steps.
Info:     Processing Sensors.
Info:     Processing Plys.
Info:     Processing Laminates.
Info:     Processing Designvars.
Info:     Processing Beamsectcols.
Info:     Processing Beamsections.
Info:     Processing Optitableentrs.
Info:     Processing Dequations.
Info:     Processing Optiresponses.
Info:     Processing Dvprels.
Info:     Processing Opticonstraints.
Info:     Processing Desvarlinks.
Info:     Processing Objectives.
Info:     Processing Opticontrols.
Info:     Processing Optidscreens.
Info:     Processing Tags.
Info:     Processing Dobjrefs.
Info:     Processing Contactsurfs.
Info:     Processing Shapes.
Info:     Processing Ddvals.
Info:     Processing Joints.
Info:     Processing Mechanismconstraints.
Info:     Processing Rigidwalls.
Info:     Processing Failures.
Info:     Processing Crosssections.
Info:     Processing Hourglass.
Info:     Processing Rigidbodies.
Info:     Processing Bodies.
Info:     Processing Mechanisms.
Info:     Processing Transformations.
Info:     Processing Positions.
Info:     Processing Outputrequests.
Info:     Processing Directmatrixinputs.
Info:     Processing Equivalences.
Info:     Processing Solvermasses.
Info:     Processing Analysisparameters.
Info:     Processing Parameters.

Summary:  Feinput finished with 0 errors and 0 warnings.
Info:     Translation Complete.
Info:     Reading OPTISTRUCT from C:/Users/sihol/OneDrive/Desktop/ASE/MATLAB/RESULT FILES/ASE_Project2025_SuperPanel_3787415_redesign.fem using C:\Program Files\Altair\2023.1\hwdesktop\io\model_readers\feinput\bin\win64\optistruct.exe on 07-03-2025 02:36:24.
Info:     Processing Modules.
Info:     Processing Cards.
Info:     Processing System Collectors.
Info:     Processing Systems.
Info:     Processing Nodes.
Info:     Processing Vectorcols.
Info:     Processing Vectors.
Info:     Processing Materials.
Info:     Processing Properties.
Info:     Processing Components.
Info:     Processing Groups.
Info:     Processing Elements.
Info:     Processing Load Collectors.
Info:     Processing Equations.
Info:     Processing Loads.
Info:     Processing Assemblies.
Info:     Processing Curves.
Info:     Processing Blocks.
Info:     Processing Sets.
Info:     Processing Output Blocks.
Info:     Processing Load Steps.
Info:     Processing Sensors.
Info:     Processing Plys.
Info:     Processing Laminates.
Info:     Processing Designvars.
Info:     Processing Beamsectcols.
Info:     Processing Beamsections.
Info:     Processing Optitableentrs.
Info:     Processing Dequations.
Info:     Processing Optiresponses.
Info:     Processing Dvprels.
Info:     Processing Opticonstraints.
Info:     Processing Desvarlinks.
Info:     Processing Objectives.
Info:     Processing Opticontrols.
Info:     Processing Optidscreens.
Info:     Processing Tags.
Info:     Processing Dobjrefs.
Info:     Processing Contactsurfs.
Info:     Processing Shapes.
Info:     Processing Ddvals.
Info:     Processing Joints.
Info:     Processing Mechanismconstraints.
Info:     Processing Rigidwalls.
Info:     Processing Failures.
Info:     Processing Crosssections.
Info:     Processing Hourglass.
Info:     Processing Rigidbodies.
Info:     Processing Bodies.
Info:     Processing Mechanisms.
Info:     Processing Transformations.
Info:     Processing Positions.
Info:     Processing Outputrequests.
Info:     Processing Directmatrixinputs.
Info:     Processing Equivalences.
Info:     Processing Solvermasses.
Info:     Processing Analysisparameters.
Info:     Processing Parameters.

Summary:  Feinput finished with 0 errors and 0 warnings.
Info:     Translation Complete.
Info:     Reading OPTISTRUCT from C:/Users/sihol/OneDrive/Desktop/ASE/MATLAB/RESULT FILES/ASE_Project2025_SuperPanel_3787415_redesign.fem using C:\Program Files\Altair\2023.1\hwdesktop\io\model_readers\feinput\bin\win64\optistruct.exe on 07-03-2025 13:23:33.
Info:     Processing Modules.
Info:     Processing Cards.
Info:     Processing System Collectors.
Info:     Processing Systems.
Info:     Processing Nodes.
Info:     Processing Vectorcols.
Info:     Processing Vectors.
Info:     Processing Materials.
Info:     Processing Properties.
Info:     Processing Components.
Info:     Processing Groups.
Info:     Processing Elements.
Info:     Processing Load Collectors.
Info:     Processing Equations.
Info:     Processing Loads.
Info:     Processing Assemblies.
Info:     Processing Curves.
Info:     Processing Blocks.
Info:     Processing Sets.
Info:     Processing Output Blocks.
Info:     Processing Load Steps.
Info:     Processing Sensors.
Info:     Processing Plys.
Info:     Processing Laminates.
Info:     Processing Designvars.
Info:     Processing Beamsectcols.
Info:     Processing Beamsections.
Info:     Processing Optitableentrs.
Info:     Processing Dequations.
Info:     Processing Optiresponses.
Info:     Processing Dvprels.
Info:     Processing Opticonstraints.
Info:     Processing Desvarlinks.
Info:     Processing Objectives.
Info:     Processing Opticontrols.
Info:     Processing Optidscreens.
Info:     Processing Tags.
Info:     Processing Dobjrefs.
Info:     Processing Contactsurfs.
Info:     Processing Shapes.
Info:     Processing Ddvals.
Info:     Processing Joints.
Info:     Processing Mechanismconstraints.
Info:     Processing Rigidwalls.
Info:     Processing Failures.
Info:     Processing Crosssections.
Info:     Processing Hourglass.
Info:     Processing Rigidbodies.
Info:     Processing Bodies.
Info:     Processing Mechanisms.
Info:     Processing Transformations.
Info:     Processing Positions.
Info:     Processing Outputrequests.
Info:     Processing Directmatrixinputs.
Info:     Processing Equivalences.
Info:     Processing Solvermasses.
Info:     Processing Analysisparameters.
Info:     Processing Parameters.

Summary:  Feinput finished with 0 errors and 0 warnings.
Info:     Translation Complete.
Info:     Reading OPTISTRUCT from C:/Users/sihol/OneDrive/Desktop/ASE/MATLAB/RESULT FILES/ASE_Project2025_SuperPanel_3787415_redesign.fem using C:\Program Files\Altair\2023.1\hwdesktop\io\model_readers\feinput\bin\win64\optistruct.exe on 07-03-2025 13:24:04.
Info:     Processing Modules.
Info:     Processing Cards.
Info:     Processing System Collectors.
Info:     Processing Systems.
Info:     Processing Nodes.
Info:     Processing Vectorcols.
Info:     Processing Vectors.
Info:     Processing Materials.
Info:     Processing Properties.
Info:     Processing Components.
Info:     Processing Groups.
Info:     Processing Elements.
Info:     Processing Load Collectors.
Info:     Processing Equations.
Info:     Processing Loads.
Info:     Processing Assemblies.
Info:     Processing Curves.
Info:     Processing Blocks.
Info:     Processing Sets.
Info:     Processing Output Blocks.
Info:     Processing Load Steps.
Info:     Processing Sensors.
Info:     Processing Plys.
Info:     Processing Laminates.
Info:     Processing Designvars.
Info:     Processing Beamsectcols.
Info:     Processing Beamsections.
Info:     Processing Optitableentrs.
Info:     Processing Dequations.
Info:     Processing Optiresponses.
Info:     Processing Dvprels.
Info:     Processing Opticonstraints.
Info:     Processing Desvarlinks.
Info:     Processing Objectives.
Info:     Processing Opticontrols.
Info:     Processing Optidscreens.
Info:     Processing Tags.
Info:     Processing Dobjrefs.
Info:     Processing Contactsurfs.
Info:     Processing Shapes.
Info:     Processing Ddvals.
Info:     Processing Joints.
Info:     Processing Mechanismconstraints.
Info:     Processing Rigidwalls.
Info:     Processing Failures.
Info:     Processing Crosssections.
Info:     Processing Hourglass.
Info:     Processing Rigidbodies.
Info:     Processing Bodies.
Info:     Processing Mechanisms.
Info:     Processing Transformations.
Info:     Processing Positions.
Info:     Processing Outputrequests.
Info:     Processing Directmatrixinputs.
Info:     Processing Equivalences.
Info:     Processing Solvermasses.
Info:     Processing Analysisparameters.
Info:     Processing Parameters.

Summary:  Feinput finished with 0 errors and 0 warnings.
Info:     Translation Complete.
Info:     Reading OPTISTRUCT from C:/Users/sihol/OneDrive/Desktop/ASE/MATLAB/RESULT FILES/ASE_Project2025_SuperPanel_3787415_redesign.fem using C:\Program Files\Altair\2023.1\hwdesktop\io\model_readers\feinput\bin\win64\optistruct.exe on 07-03-2025 13:25:09.
Info:     Processing Modules.
Info:     Processing Cards.
Info:     Processing System Collectors.
Info:     Processing Systems.
Info:     Processing Nodes.
Info:     Processing Vectorcols.
Info:     Processing Vectors.
Info:     Processing Materials.
Info:     Processing Properties.
Info:     Processing Components.
Info:     Processing Groups.
Info:     Processing Elements.
Info:     Processing Load Collectors.
Info:     Processing Equations.
Info:     Processing Loads.
Info:     Processing Assemblies.
Info:     Processing Curves.
Info:     Processing Blocks.
Info:     Processing Sets.
Info:     Processing Output Blocks.
Info:     Processing Load Steps.
Info:     Processing Sensors.
Info:     Processing Plys.
Info:     Processing Laminates.
Info:     Processing Designvars.
Info:     Processing Beamsectcols.
Info:     Processing Beamsections.
Info:     Processing Optitableentrs.
Info:     Processing Dequations.
Info:     Processing Optiresponses.
Info:     Processing Dvprels.
Info:     Processing Opticonstraints.
Info:     Processing Desvarlinks.
Info:     Processing Objectives.
Info:     Processing Opticontrols.
Info:     Processing Optidscreens.
Info:     Processing Tags.
Info:     Processing Dobjrefs.
Info:     Processing Contactsurfs.
Info:     Processing Shapes.
Info:     Processing Ddvals.
Info:     Processing Joints.
Info:     Processing Mechanismconstraints.
Info:     Processing Rigidwalls.
Info:     Processing Failures.
Info:     Processing Crosssections.
Info:     Processing Hourglass.
Info:     Processing Rigidbodies.
Info:     Processing Bodies.
Info:     Processing Mechanisms.
Info:     Processing Transformations.
Info:     Processing Positions.
Info:     Processing Outputrequests.
Info:     Processing Directmatrixinputs.
Info:     Processing Equivalences.
Info:     Processing Solvermasses.
Info:     Processing Analysisparameters.
Info:     Processing Parameters.

Summary:  Feinput finished with 0 errors and 0 warnings.
Info:     Translation Complete.
Info:     Reading OPTISTRUCT from C:/Users/sihol/OneDrive/Desktop/ASE/MATLAB/RESULT FILES/ASE_Project2025_SuperPanel_3787415_redesign.fem using C:\Program Files\Altair\2023.1\hwdesktop\io\model_readers\feinput\bin\win64\optistruct.exe on 07-03-2025 13:27:58.
Info:     Processing Modules.
Info:     Processing Cards.
Info:     Processing System Collectors.
Info:     Processing Systems.
Info:     Processing Nodes.
Info:     Processing Vectorcols.
Info:     Processing Vectors.
Info:     Processing Materials.
Info:     Processing Properties.
Info:     Processing Components.
Info:     Processing Groups.
Info:     Processing Elements.
Info:     Processing Load Collectors.
Info:     Processing Equations.
Info:     Processing Loads.
Info:     Processing Assemblies.
Info:     Processing Curves.
Info:     Processing Blocks.
Info:     Processing Sets.
Info:     Processing Output Blocks.
Info:     Processing Load Steps.
Info:     Processing Sensors.
Info:     Processing Plys.
Info:     Processing Laminates.
Info:     Processing Designvars.
Info:     Processing Beamsectcols.
Info:     Processing Beamsections.
Info:     Processing Optitableentrs.
Info:     Processing Dequations.
Info:     Processing Optiresponses.
Info:     Processing Dvprels.
Info:     Processing Opticonstraints.
Info:     Processing Desvarlinks.
Info:     Processing Objectives.
Info:     Processing Opticontrols.
Info:     Processing Optidscreens.
Info:     Processing Tags.
Info:     Processing Dobjrefs.
Info:     Processing Contactsurfs.
Info:     Processing Shapes.
Info:     Processing Ddvals.
Info:     Processing Joints.
Info:     Processing Mechanismconstraints.
Info:     Processing Rigidwalls.
Info:     Processing Failures.
Info:     Processing Crosssections.
Info:     Processing Hourglass.
Info:     Processing Rigidbodies.
Info:     Processing Bodies.
Info:     Processing Mechanisms.
Info:     Processing Transformations.
Info:     Processing Positions.
Info:     Processing Outputrequests.
Info:     Processing Directmatrixinputs.
Info:     Processing Equivalences.
Info:     Processing Solvermasses.
Info:     Processing Analysisparameters.
Info:     Processing Parameters.

Summary:  Feinput finished with 0 errors and 0 warnings.
Info:     Translation Complete.
Info:     Reading OPTISTRUCT from C:/Users/sihol/OneDrive/Desktop/ASE/MATLAB/RESULT FILES/ASE_Project2025_SuperPanel_3784167_redesign.fem using C:\Program Files\Altair\2023.1\hwdesktop\io\model_readers\feinput\bin\win64\optistruct.exe on 07-03-2025 13:29:48.
Info:     Processing Modules.
Info:     Processing Cards.
Info:     Processing System Collectors.
Info:     Processing Systems.
Info:     Processing Nodes.
Info:     Processing Vectorcols.
Info:     Processing Vectors.
Info:     Processing Materials.
Info:     Processing Properties.
Info:     Processing Components.
Info:     Processing Groups.
Info:     Processing Elements.
Info:     Processing Load Collectors.
Info:     Processing Equations.
Info:     Processing Loads.
Info:     Processing Assemblies.
Info:     Processing Curves.
Info:     Processing Blocks.
Info:     Processing Sets.
Info:     Processing Output Blocks.
Info:     Processing Load Steps.
Info:     Processing Sensors.
Info:     Processing Plys.
Info:     Processing Laminates.
Info:     Processing Designvars.
Info:     Processing Beamsectcols.
Info:     Processing Beamsections.
Info:     Processing Optitableentrs.
Info:     Processing Dequations.
Info:     Processing Optiresponses.
Info:     Processing Dvprels.
Info:     Processing Opticonstraints.
Info:     Processing Desvarlinks.
Info:     Processing Objectives.
Info:     Processing Opticontrols.
Info:     Processing Optidscreens.
Info:     Processing Tags.
Info:     Processing Dobjrefs.
Info:     Processing Contactsurfs.
Info:     Processing Shapes.
Info:     Processing Ddvals.
Info:     Processing Joints.
Info:     Processing Mechanismconstraints.
Info:     Processing Rigidwalls.
Info:     Processing Failures.
Info:     Processing Crosssections.
Info:     Processing Hourglass.
Info:     Processing Rigidbodies.
Info:     Processing Bodies.
Info:     Processing Mechanisms.
Info:     Processing Transformations.
Info:     Processing Positions.
Info:     Processing Outputrequests.
Info:     Processing Directmatrixinputs.
Info:     Processing Equivalences.
Info:     Processing Solvermasses.
Info:     Processing Analysisparameters.
Info:     Processing Parameters.

Summary:  Feinput finished with 0 errors and 0 warnings.
Info:     Translation Complete.
Info:     Reading OPTISTRUCT from C:/Users/sihol/OneDrive/Desktop/ASE/MATLAB/RESULT FILES/ASE_Project2025_SuperPanel_3783738_redesign.fem using C:\Program Files\Altair\2023.1\hwdesktop\io\model_readers\feinput\bin\win64\optistruct.exe on 07-03-2025 13:34:40.
Info:     Processing Modules.
Info:     Processing Cards.
Info:     Processing System Collectors.
Info:     Processing Systems.
Info:     Processing Nodes.
Info:     Processing Vectorcols.
Info:     Processing Vectors.
Info:     Processing Materials.
Info:     Processing Properties.
Info:     Processing Components.
Info:     Processing Groups.
Info:     Processing Elements.
Info:     Processing Load Collectors.
Info:     Processing Equations.
Info:     Processing Loads.
Info:     Processing Assemblies.
Info:     Processing Curves.
Info:     Processing Blocks.
Info:     Processing Sets.
Info:     Processing Output Blocks.
Info:     Processing Load Steps.
Info:     Processing Sensors.
Info:     Processing Plys.
Info:     Processing Laminates.
Info:     Processing Designvars.
Info:     Processing Beamsectcols.
Info:     Processing Beamsections.
Info:     Processing Optitableentrs.
Info:     Processing Dequations.
Info:     Processing Optiresponses.
Info:     Processing Dvprels.
Info:     Processing Opticonstraints.
Info:     Processing Desvarlinks.
Info:     Processing Objectives.
Info:     Processing Opticontrols.
Info:     Processing Optidscreens.
Info:     Processing Tags.
Info:     Processing Dobjrefs.
Info:     Processing Contactsurfs.
Info:     Processing Shapes.
Info:     Processing Ddvals.
Info:     Processing Joints.
Info:     Processing Mechanismconstraints.
Info:     Processing Rigidwalls.
Info:     Processing Failures.
Info:     Processing Crosssections.
Info:     Processing Hourglass.
Info:     Processing Rigidbodies.
Info:     Processing Bodies.
Info:     Processing Mechanisms.
Info:     Processing Transformations.
Info:     Processing Positions.
Info:     Processing Outputrequests.
Info:     Processing Directmatrixinputs.
Info:     Processing Equivalences.
Info:     Processing Solvermasses.
Info:     Processing Analysisparameters.
Info:     Processing Parameters.

Summary:  Feinput finished with 0 errors and 0 warnings.
Info:     Translation Complete.
Info:     Reading OPTISTRUCT from C:/Users/sihol/OneDrive/Desktop/ASE/MATLAB/RESULT FILES/ASE_Project2025_SuperPanel_3787415_redesign.fem using C:\Program Files\Altair\2023.1\hwdesktop\io\model_readers\feinput\bin\win64\optistruct.exe on 07-03-2025 13:40:16.
Info:     Processing Modules.
Info:     Processing Cards.
Info:     Processing System Collectors.
Info:     Processing Systems.
Info:     Processing Nodes.
Info:     Processing Vectorcols.
Info:     Processing Vectors.
Info:     Processing Materials.
Info:     Processing Properties.
Info:     Processing Components.
Info:     Processing Groups.
Info:     Processing Elements.
Info:     Processing Load Collectors.
Info:     Processing Equations.
Info:     Processing Loads.
Info:     Processing Assemblies.
Info:     Processing Curves.
Info:     Processing Blocks.
Info:     Processing Sets.
Info:     Processing Output Blocks.
Info:     Processing Load Steps.
Info:     Processing Sensors.
Info:     Processing Plys.
Info:     Processing Laminates.
Info:     Processing Designvars.
Info:     Processing Beamsectcols.
Info:     Processing Beamsections.
Info:     Processing Optitableentrs.
Info:     Processing Dequations.
Info:     Processing Optiresponses.
Info:     Processing Dvprels.
Info:     Processing Opticonstraints.
Info:     Processing Desvarlinks.
Info:     Processing Objectives.
Info:     Processing Opticontrols.
Info:     Processing Optidscreens.
Info:     Processing Tags.
Info:     Processing Dobjrefs.
Info:     Processing Contactsurfs.
Info:     Processing Shapes.
Info:     Processing Ddvals.
Info:     Processing Joints.
Info:     Processing Mechanismconstraints.
Info:     Processing Rigidwalls.
Info:     Processing Failures.
Info:     Processing Crosssections.
Info:     Processing Hourglass.
Info:     Processing Rigidbodies.
Info:     Processing Bodies.
Info:     Processing Mechanisms.
Info:     Processing Transformations.
Info:     Processing Positions.
Info:     Processing Outputrequests.
Info:     Processing Directmatrixinputs.
Info:     Processing Equivalences.
Info:     Processing Solvermasses.
Info:     Processing Analysisparameters.
Info:     Processing Parameters.

Summary:  Feinput finished with 0 errors and 0 warnings.
Info:     Translation Complete.
Info:     Reading OPTISTRUCT from C:/Users/sihol/OneDrive/Desktop/ASE/MATLAB/RESULT FILES/ASE_Project2025_SuperPanel_3787415_redesign.fem using C:\Program Files\Altair\2023.1\hwdesktop\io\model_readers\feinput\bin\win64\optistruct.exe on 07-03-2025 14:04:05.
Info:     Processing Modules.
Info:     Processing Cards.
Info:     Processing System Collectors.
Info:     Processing Systems.
Info:     Processing Nodes.
Info:     Processing Vectorcols.
Info:     Processing Vectors.
Info:     Processing Materials.
Info:     Processing Properties.
Info:     Processing Components.
Info:     Processing Groups.
Info:     Processing Elements.
Info:     Processing Load Collectors.
Info:     Processing Equations.
Info:     Processing Loads.
Info:     Processing Assemblies.
Info:     Processing Curves.
Info:     Processing Blocks.
Info:     Processing Sets.
Info:     Processing Output Blocks.
Info:     Processing Load Steps.
Info:     Processing Sensors.
Info:     Processing Plys.
Info:     Processing Laminates.
Info:     Processing Designvars.
Info:     Processing Beamsectcols.
Info:     Processing Beamsections.
Info:     Processing Optitableentrs.
Info:     Processing Dequations.
Info:     Processing Optiresponses.
Info:     Processing Dvprels.
Info:     Processing Opticonstraints.
Info:     Processing Desvarlinks.
Info:     Processing Objectives.
Info:     Processing Opticontrols.
Info:     Processing Optidscreens.
Info:     Processing Tags.
Info:     Processing Dobjrefs.
Info:     Processing Contactsurfs.
Info:     Processing Shapes.
Info:     Processing Ddvals.
Info:     Processing Joints.
Info:     Processing Mechanismconstraints.
Info:     Processing Rigidwalls.
Info:     Processing Failures.
Info:     Processing Crosssections.
Info:     Processing Hourglass.
Info:     Processing Rigidbodies.
Info:     Processing Bodies.
Info:     Processing Mechanisms.
Info:     Processing Transformations.
Info:     Processing Positions.
Info:     Processing Outputrequests.
Info:     Processing Directmatrixinputs.
Info:     Processing Equivalences.
Info:     Processing Solvermasses.
Info:     Processing Analysisparameters.
Info:     Processing Parameters.

Summary:  Feinput finished with 0 errors and 0 warnings.
Info:     Translation Complete.
Info:     Reading OPTISTRUCT from C:/Users/sihol/OneDrive/Desktop/ASE/MATLAB/RESULT FILES/ASE_Project2025_SuperPanel_3787415_redesign.fem using C:\Program Files\Altair\2023.1\hwdesktop\io\model_readers\feinput\bin\win64\optistruct.exe on 07-03-2025 14:20:04.
Info:     Processing Modules.
Info:     Processing Cards.
Info:     Processing System Collectors.
Info:     Processing Systems.
Info:     Processing Nodes.
Info:     Processing Vectorcols.
Info:     Processing Vectors.
Info:     Processing Materials.
Info:     Processing Properties.
Info:     Processing Components.
Info:     Processing Groups.
Info:     Processing Elements.
Info:     Processing Load Collectors.
Info:     Processing Equations.
Info:     Processing Loads.
Info:     Processing Assemblies.
Info:     Processing Curves.
Info:     Processing Blocks.
Info:     Processing Sets.
Info:     Processing Output Blocks.
Info:     Processing Load Steps.
Info:     Processing Sensors.
Info:     Processing Plys.
Info:     Processing Laminates.
Info:     Processing Designvars.
Info:     Processing Beamsectcols.
Info:     Processing Beamsections.
Info:     Processing Optitableentrs.
Info:     Processing Dequations.
Info:     Processing Optiresponses.
Info:     Processing Dvprels.
Info:     Processing Opticonstraints.
Info:     Processing Desvarlinks.
Info:     Processing Objectives.
Info:     Processing Opticontrols.
Info:     Processing Optidscreens.
Info:     Processing Tags.
Info:     Processing Dobjrefs.
Info:     Processing Contactsurfs.
Info:     Processing Shapes.
Info:     Processing Ddvals.
Info:     Processing Joints.
Info:     Processing Mechanismconstraints.
Info:     Processing Rigidwalls.
Info:     Processing Failures.
Info:     Processing Crosssections.
Info:     Processing Hourglass.
Info:     Processing Rigidbodies.
Info:     Processing Bodies.
Info:     Processing Mechanisms.
Info:     Processing Transformations.
Info:     Processing Positions.
Info:     Processing Outputrequests.
Info:     Processing Directmatrixinputs.
Info:     Processing Equivalences.
Info:     Processing Solvermasses.
Info:     Processing Analysisparameters.
Info:     Processing Parameters.

Summary:  Feinput finished with 0 errors and 0 warnings.
Info:     Translation Complete.
Info:     Reading OPTISTRUCT from C:/Users/sihol/OneDrive/Desktop/ASE/MATLAB/RESULT FILES/ASE_Project2025_SuperPanel_3787415_redesign.fem using C:\Program Files\Altair\2023.1\hwdesktop\io\model_readers\feinput\bin\win64\optistruct.exe on 07-03-2025 14:37:40.
Info:     Processing Modules.
Info:     Processing Cards.
Info:     Processing System Collectors.
Info:     Processing Systems.
Info:     Processing Nodes.
Info:     Processing Vectorcols.
Info:     Processing Vectors.
Info:     Processing Materials.
Info:     Processing Properties.
Info:     Processing Components.
Info:     Processing Groups.
Info:     Processing Elements.
Info:     Processing Load Collectors.
Info:     Processing Equations.
Info:     Processing Loads.
Info:     Processing Assemblies.
Info:     Processing Curves.
Info:     Processing Blocks.
Info:     Processing Sets.
Info:     Processing Output Blocks.
Info:     Processing Load Steps.
Info:     Processing Sensors.
Info:     Processing Plys.
Info:     Processing Laminates.
Info:     Processing Designvars.
Info:     Processing Beamsectcols.
Info:     Processing Beamsections.
Info:     Processing Optitableentrs.
Info:     Processing Dequations.
Info:     Processing Optiresponses.
Info:     Processing Dvprels.
Info:     Processing Opticonstraints.
Info:     Processing Desvarlinks.
Info:     Processing Objectives.
Info:     Processing Opticontrols.
Info:     Processing Optidscreens.
Info:     Processing Tags.
Info:     Processing Dobjrefs.
Info:     Processing Contactsurfs.
Info:     Processing Shapes.
Info:     Processing Ddvals.
Info:     Processing Joints.
Info:     Processing Mechanismconstraints.
Info:     Processing Rigidwalls.
Info:     Processing Failures.
Info:     Processing Crosssections.
Info:     Processing Hourglass.
Info:     Processing Rigidbodies.
Info:     Processing Bodies.
Info:     Processing Mechanisms.
Info:     Processing Transformations.
Info:     Processing Positions.
Info:     Processing Outputrequests.
Info:     Processing Directmatrixinputs.
Info:     Processing Equivalences.
Info:     Processing Solvermasses.
Info:     Processing Analysisparameters.
Info:     Processing Parameters.

Summary:  Feinput finished with 0 errors and 0 warnings.
Info:     Translation Complete.
Info:     Reading OPTISTRUCT from C:/Users/sihol/OneDrive/Desktop/ASE/MATLAB/RESULT FILES/ASE_Project2025_SuperPanel_3787415_redesign.fem using C:\Program Files\Altair\2023.1\hwdesktop\io\model_readers\feinput\bin\win64\optistruct.exe on 07-03-2025 15:39:10.
Info:     Processing Modules.
Info:     Processing Cards.
Info:     Processing System Collectors.
Info:     Processing Systems.
Info:     Processing Nodes.
Info:     Processing Vectorcols.
Info:     Processing Vectors.
Info:     Processing Materials.
Info:     Processing Properties.
Info:     Processing Components.
Info:     Processing Groups.
Info:     Processing Elements.
Info:     Processing Load Collectors.
Info:     Processing Equations.
Info:     Processing Loads.
Info:     Processing Assemblies.
Info:     Processing Curves.
Info:     Processing Blocks.
Info:     Processing Sets.
Info:     Processing Output Blocks.
Info:     Processing Load Steps.
Info:     Processing Sensors.
Info:     Processing Plys.
Info:     Processing Laminates.
Info:     Processing Designvars.
Info:     Processing Beamsectcols.
Info:     Processing Beamsections.
Info:     Processing Optitableentrs.
Info:     Processing Dequations.
Info:     Processing Optiresponses.
Info:     Processing Dvprels.
Info:     Processing Opticonstraints.
Info:     Processing Desvarlinks.
Info:     Processing Objectives.
Info:     Processing Opticontrols.
Info:     Processing Optidscreens.
Info:     Processing Tags.
Info:     Processing Dobjrefs.
Info:     Processing Contactsurfs.
Info:     Processing Shapes.
Info:     Processing Ddvals.
Info:     Processing Joints.
Info:     Processing Mechanismconstraints.
Info:     Processing Rigidwalls.
Info:     Processing Failures.
Info:     Processing Crosssections.
Info:     Processing Hourglass.
Info:     Processing Rigidbodies.
Info:     Processing Bodies.
Info:     Processing Mechanisms.
Info:     Processing Transformations.
Info:     Processing Positions.
Info:     Processing Outputrequests.
Info:     Processing Directmatrixinputs.
Info:     Processing Equivalences.
Info:     Processing Solvermasses.
Info:     Processing Analysisparameters.
Info:     Processing Parameters.

Summary:  Feinput finished with 0 errors and 0 warnings.
Info:     Translation Complete.
Info:     Reading OPTISTRUCT from C:/Users/sihol/OneDrive/Desktop/ASE/MATLAB/RESULT FILES/ASE_Project2025_SuperPanel_3787415_redesign.fem using C:\Program Files\Altair\2023.1\hwdesktop\io\model_readers\feinput\bin\win64\optistruct.exe on 07-03-2025 15:40:22.
Info:     Processing Modules.
Info:     Processing Cards.
Info:     Processing System Collectors.
Info:     Processing Systems.
Info:     Processing Nodes.
Info:     Processing Vectorcols.
Info:     Processing Vectors.
Info:     Processing Materials.
Info:     Processing Properties.
Info:     Processing Components.
Info:     Processing Groups.
Info:     Processing Elements.
Info:     Processing Load Collectors.
Info:     Processing Equations.
Info:     Processing Loads.
Info:     Processing Assemblies.
Info:     Processing Curves.
Info:     Processing Blocks.
Info:     Processing Sets.
Info:     Processing Output Blocks.
Info:     Processing Load Steps.
Info:     Processing Sensors.
Info:     Processing Plys.
Info:     Processing Laminates.
Info:     Processing Designvars.
Info:     Processing Beamsectcols.
Info:     Processing Beamsections.
Info:     Processing Optitableentrs.
Info:     Processing Dequations.
Info:     Processing Optiresponses.
Info:     Processing Dvprels.
Info:     Processing Opticonstraints.
Info:     Processing Desvarlinks.
Info:     Processing Objectives.
Info:     Processing Opticontrols.
Info:     Processing Optidscreens.
Info:     Processing Tags.
Info:     Processing Dobjrefs.
Info:     Processing Contactsurfs.
Info:     Processing Shapes.
Info:     Processing Ddvals.
Info:     Processing Joints.
Info:     Processing Mechanismconstraints.
Info:     Processing Rigidwalls.
Info:     Processing Failures.
Info:     Processing Crosssections.
Info:     Processing Hourglass.
Info:     Processing Rigidbodies.
Info:     Processing Bodies.
Info:     Processing Mechanisms.
Info:     Processing Transformations.
Info:     Processing Positions.
Info:     Processing Outputrequests.
Info:     Processing Directmatrixinputs.
Info:     Processing Equivalences.
Info:     Processing Solvermasses.
Info:     Processing Analysisparameters.
Info:     Processing Parameters.

Summary:  Feinput finished with 0 errors and 0 warnings.
Info:     Translation Complete.
Info:     Reading OPTISTRUCT from C:/Users/sihol/OneDrive/Desktop/ASE/MATLAB/RESULT FILES/ASE_Project2025_SuperPanel_3783738_redesign.fem using C:\Program Files\Altair\2023.1\hwdesktop\io\model_readers\feinput\bin\win64\optistruct.exe on 07-03-2025 15:43:07.
Info:     Processing Modules.
Info:     Processing Cards.
Info:     Processing System Collectors.
Info:     Processing Systems.
Info:     Processing Nodes.
Info:     Processing Vectorcols.
Info:     Processing Vectors.
Info:     Processing Materials.
Info:     Processing Properties.
Info:     Processing Components.
Info:     Processing Groups.
Info:     Processing Elements.
Info:     Processing Load Collectors.
Info:     Processing Equations.
Info:     Processing Loads.
Info:     Processing Assemblies.
Info:     Processing Curves.
Info:     Processing Blocks.
Info:     Processing Sets.
Info:     Processing Output Blocks.
Info:     Processing Load Steps.
Info:     Processing Sensors.
Info:     Processing Plys.
Info:     Processing Laminates.
Info:     Processing Designvars.
Info:     Processing Beamsectcols.
Info:     Processing Beamsections.
Info:     Processing Optitableentrs.
Info:     Processing Dequations.
Info:     Processing Optiresponses.
Info:     Processing Dvprels.
Info:     Processing Opticonstraints.
Info:     Processing Desvarlinks.
Info:     Processing Objectives.
Info:     Processing Opticontrols.
Info:     Processing Optidscreens.
Info:     Processing Tags.
Info:     Processing Dobjrefs.
Info:     Processing Contactsurfs.
Info:     Processing Shapes.
Info:     Processing Ddvals.
Info:     Processing Joints.
Info:     Processing Mechanismconstraints.
Info:     Processing Rigidwalls.
Info:     Processing Failures.
Info:     Processing Crosssections.
Info:     Processing Hourglass.
Info:     Processing Rigidbodies.
Info:     Processing Bodies.
Info:     Processing Mechanisms.
Info:     Processing Transformations.
Info:     Processing Positions.
Info:     Processing Outputrequests.
Info:     Processing Directmatrixinputs.
Info:     Processing Equivalences.
Info:     Processing Solvermasses.
Info:     Processing Analysisparameters.
Info:     Processing Parameters.

Summary:  Feinput finished with 0 errors and 0 warnings.
Info:     Translation Complete.
Info:     Reading OPTISTRUCT from C:/Users/sihol/OneDrive/Desktop/ASE/MATLAB/RESULT FILES/ASE_Project2025_SuperPanel_3787415_redesign.fem using C:\Program Files\Altair\2023.1\hwdesktop\io\model_readers\feinput\bin\win64\optistruct.exe on 07-03-2025 15:44:27.
Info:     Processing Modules.
Info:     Processing Cards.
Info:     Processing System Collectors.
Info:     Processing Systems.
Info:     Processing Nodes.
Info:     Processing Vectorcols.
Info:     Processing Vectors.
Info:     Processing Materials.
Info:     Processing Properties.
Info:     Processing Components.
Info:     Processing Groups.
Info:     Processing Elements.
Info:     Processing Load Collectors.
Info:     Processing Equations.
Info:     Processing Loads.
Info:     Processing Assemblies.
Info:     Processing Curves.
Info:     Processing Blocks.
Info:     Processing Sets.
Info:     Processing Output Blocks.
Info:     Processing Load Steps.
Info:     Processing Sensors.
Info:     Processing Plys.
Info:     Processing Laminates.
Info:     Processing Designvars.
Info:     Processing Beamsectcols.
Info:     Processing Beamsections.
Info:     Processing Optitableentrs.
Info:     Processing Dequations.
Info:     Processing Optiresponses.
Info:     Processing Dvprels.
Info:     Processing Opticonstraints.
Info:     Processing Desvarlinks.
Info:     Processing Objectives.
Info:     Processing Opticontrols.
Info:     Processing Optidscreens.
Info:     Processing Tags.
Info:     Processing Dobjrefs.
Info:     Processing Contactsurfs.
Info:     Processing Shapes.
Info:     Processing Ddvals.
Info:     Processing Joints.
Info:     Processing Mechanismconstraints.
Info:     Processing Rigidwalls.
Info:     Processing Failures.
Info:     Processing Crosssections.
Info:     Processing Hourglass.
Info:     Processing Rigidbodies.
Info:     Processing Bodies.
Info:     Processing Mechanisms.
Info:     Processing Transformations.
Info:     Processing Positions.
Info:     Processing Outputrequests.
Info:     Processing Directmatrixinputs.
Info:     Processing Equivalences.
Info:     Processing Solvermasses.
Info:     Processing Analysisparameters.
Info:     Processing Parameters.

Summary:  Feinput finished with 0 errors and 0 warnings.
Info:     Translation Complete.
Info:     Reading OPTISTRUCT from C:/Users/sihol/OneDrive/Desktop/ASE/MATLAB/RESULT FILES/ASE_Project2025_SuperPanel_3786505_redesign.fem using C:\Program Files\Altair\2023.1\hwdesktop\io\model_readers\feinput\bin\win64\optistruct.exe on 07-03-2025 15:45:41.
Info:     Processing Modules.
Info:     Processing Cards.
Info:     Processing System Collectors.
Info:     Processing Systems.
Info:     Processing Nodes.
Info:     Processing Vectorcols.
Info:     Processing Vectors.
Info:     Processing Materials.
Info:     Processing Properties.
Info:     Processing Components.
Info:     Processing Groups.
Info:     Processing Elements.
Info:     Processing Load Collectors.
Info:     Processing Equations.
Info:     Processing Loads.
Info:     Processing Assemblies.
Info:     Processing Curves.
Info:     Processing Blocks.
Info:     Processing Sets.
Info:     Processing Output Blocks.
Info:     Processing Load Steps.
Info:     Processing Sensors.
Info:     Processing Plys.
Info:     Processing Laminates.
Info:     Processing Designvars.
Info:     Processing Beamsectcols.
Info:     Processing Beamsections.
Info:     Processing Optitableentrs.
Info:     Processing Dequations.
Info:     Processing Optiresponses.
Info:     Processing Dvprels.
Info:     Processing Opticonstraints.
Info:     Processing Desvarlinks.
Info:     Processing Objectives.
Info:     Processing Opticontrols.
Info:     Processing Optidscreens.
Info:     Processing Tags.
Info:     Processing Dobjrefs.
Info:     Processing Contactsurfs.
Info:     Processing Shapes.
Info:     Processing Ddvals.
Info:     Processing Joints.
Info:     Processing Mechanismconstraints.
Info:     Processing Rigidwalls.
Info:     Processing Failures.
Info:     Processing Crosssections.
Info:     Processing Hourglass.
Info:     Processing Rigidbodies.
Info:     Processing Bodies.
Info:     Processing Mechanisms.
Info:     Processing Transformations.
Info:     Processing Positions.
Info:     Processing Outputrequests.
Info:     Processing Directmatrixinputs.
Info:     Processing Equivalences.
Info:     Processing Solvermasses.
Info:     Processing Analysisparameters.
Info:     Processing Parameters.

Summary:  Feinput finished with 0 errors and 0 warnings.
Info:     Translation Complete.
Info:     Reading OPTISTRUCT from C:/Users/sihol/OneDrive/Desktop/ASE/MATLAB/RESULT FILES/ASE_Project2025_SuperPanel_3787415_redesign.fem using C:\Program Files\Altair\2023.1\hwdesktop\io\model_readers\feinput\bin\win64\optistruct.exe on 07-05-2025 22:14:32.
Info:     Processing Modules.
Info:     Processing Cards.
Info:     Processing System Collectors.
Info:     Processing Systems.
Info:     Processing Nodes.
Info:     Processing Vectorcols.
Info:     Processing Vectors.
Info:     Processing Materials.
Info:     Processing Properties.
Info:     Processing Components.
Info:     Processing Groups.
Info:     Processing Elements.
Info:     Processing Load Collectors.
Info:     Processing Equations.
Info:     Processing Loads.
Info:     Processing Assemblies.
Info:     Processing Curves.
Info:     Processing Blocks.
Info:     Processing Sets.
Info:     Processing Output Blocks.
Info:     Processing Load Steps.
Info:     Processing Sensors.
Info:     Processing Plys.
Info:     Processing Laminates.
Info:     Processing Designvars.
Info:     Processing Beamsectcols.
Info:     Processing Beamsections.
Info:     Processing Optitableentrs.
Info:     Processing Dequations.
Info:     Processing Optiresponses.
Info:     Processing Dvprels.
Info:     Processing Opticonstraints.
Info:     Processing Desvarlinks.
Info:     Processing Objectives.
Info:     Processing Opticontrols.
Info:     Processing Optidscreens.
Info:     Processing Tags.
Info:     Processing Dobjrefs.
Info:     Processing Contactsurfs.
Info:     Processing Shapes.
Info:     Processing Ddvals.
Info:     Processing Joints.
Info:     Processing Mechanismconstraints.
Info:     Processing Rigidwalls.
Info:     Processing Failures.
Info:     Processing Crosssections.
Info:     Processing Hourglass.
Info:     Processing Rigidbodies.
Info:     Processing Bodies.
Info:     Processing Mechanisms.
Info:     Processing Transformations.
Info:     Processing Positions.
Info:     Processing Outputrequests.
Info:     Processing Directmatrixinputs.
Info:     Processing Equivalences.
Info:     Processing Solvermasses.
Info:     Processing Analysisparameters.
Info:     Processing Parameters.

Summary:  Feinput finished with 0 errors and 0 warnings.
Info:     Translation Complete.
Info:     Reading OPTISTRUCT from C:/Users/sihol/OneDrive/Desktop/ASE/MATLAB/RESULT FILES/ASE_Project2025_SuperPanel_3787415_redesign.fem using C:\Program Files\Altair\2023.1\hwdesktop\io\model_readers\feinput\bin\win64\optistruct.exe on 07-05-2025 22:15:43.
Info:     Processing Modules.
Info:     Processing Cards.
Info:     Processing System Collectors.
Info:     Processing Systems.
Info:     Processing Nodes.
Info:     Processing Vectorcols.
Info:     Processing Vectors.
Info:     Processing Materials.
Info:     Processing Properties.
Info:     Processing Components.
Info:     Processing Groups.
Info:     Processing Elements.
Info:     Processing Load Collectors.
Info:     Processing Equations.
Info:     Processing Loads.
Info:     Processing Assemblies.
Info:     Processing Curves.
Info:     Processing Blocks.
Info:     Processing Sets.
Info:     Processing Output Blocks.
Info:     Processing Load Steps.
Info:     Processing Sensors.
Info:     Processing Plys.
Info:     Processing Laminates.
Info:     Processing Designvars.
Info:     Processing Beamsectcols.
Info:     Processing Beamsections.
Info:     Processing Optitableentrs.
Info:     Processing Dequations.
Info:     Processing Optiresponses.
Info:     Processing Dvprels.
Info:     Processing Opticonstraints.
Info:     Processing Desvarlinks.
Info:     Processing Objectives.
Info:     Processing Opticontrols.
Info:     Processing Optidscreens.
Info:     Processing Tags.
Info:     Processing Dobjrefs.
Info:     Processing Contactsurfs.
Info:     Processing Shapes.
Info:     Processing Ddvals.
Info:     Processing Joints.
Info:     Processing Mechanismconstraints.
Info:     Processing Rigidwalls.
Info:     Processing Failures.
Info:     Processing Crosssections.
Info:     Processing Hourglass.
Info:     Processing Rigidbodies.
Info:     Processing Bodies.
Info:     Processing Mechanisms.
Info:     Processing Transformations.
Info:     Processing Positions.
Info:     Processing Outputrequests.
Info:     Processing Directmatrixinputs.
Info:     Processing Equivalences.
Info:     Processing Solvermasses.
Info:     Processing Analysisparameters.
Info:     Processing Parameters.

Summary:  Feinput finished with 0 errors and 0 warnings.
Info:     Translation Complete.
Info:     Reading OPTISTRUCT from C:/Users/sihol/OneDrive/Desktop/ASE/MATLAB/RESULT FILES/ASE_Project2025_SuperPanel_3787415_redesign.fem using C:\Program Files\Altair\2023.1\hwdesktop\io\model_readers\feinput\bin\win64\optistruct.exe on 07-05-2025 22:20:04.
Info:     Processing Modules.
Info:     Processing Cards.
Info:     Processing System Collectors.
Info:     Processing Systems.
Info:     Processing Nodes.
Info:     Processing Vectorcols.
Info:     Processing Vectors.
Info:     Processing Materials.
Info:     Processing Properties.
Info:     Processing Components.
Info:     Processing Groups.
Info:     Processing Elements.
Info:     Processing Load Collectors.
Info:     Processing Equations.
Info:     Processing Loads.
Info:     Processing Assemblies.
Info:     Processing Curves.
Info:     Processing Blocks.
Info:     Processing Sets.
Info:     Processing Output Blocks.
Info:     Processing Load Steps.
Info:     Processing Sensors.
Info:     Processing Plys.
Info:     Processing Laminates.
Info:     Processing Designvars.
Info:     Processing Beamsectcols.
Info:     Processing Beamsections.
Info:     Processing Optitableentrs.
Info:     Processing Dequations.
Info:     Processing Optiresponses.
Info:     Processing Dvprels.
Info:     Processing Opticonstraints.
Info:     Processing Desvarlinks.
Info:     Processing Objectives.
Info:     Processing Opticontrols.
Info:     Processing Optidscreens.
Info:     Processing Tags.
Info:     Processing Dobjrefs.
Info:     Processing Contactsurfs.
Info:     Processing Shapes.
Info:     Processing Ddvals.
Info:     Processing Joints.
Info:     Processing Mechanismconstraints.
Info:     Processing Rigidwalls.
Info:     Processing Failures.
Info:     Processing Crosssections.
Info:     Processing Hourglass.
Info:     Processing Rigidbodies.
Info:     Processing Bodies.
Info:     Processing Mechanisms.
Info:     Processing Transformations.
Info:     Processing Positions.
Info:     Processing Outputrequests.
Info:     Processing Directmatrixinputs.
Info:     Processing Equivalences.
Info:     Processing Solvermasses.
Info:     Processing Analysisparameters.
Info:     Processing Parameters.

Summary:  Feinput finished with 0 errors and 0 warnings.
Info:     Translation Complete.
Info:     Reading OPTISTRUCT from C:/Users/sihol/OneDrive/Desktop/ASE/MATLAB/RESULT FILES/ASE_Project2025_SuperPanel_3787415_redesign.fem using C:\Program Files\Altair\2023.1\hwdesktop\io\model_readers\feinput\bin\win64\optistruct.exe on 07-05-2025 22:27:49.
Info:     Processing Modules.
Info:     Processing Cards.
Info:     Processing System Collectors.
Info:     Processing Systems.
Info:     Processing Nodes.
Info:     Processing Vectorcols.
Info:     Processing Vectors.
Info:     Processing Materials.
Info:     Processing Properties.
Info:     Processing Components.
Info:     Processing Groups.
Info:     Processing Elements.
Info:     Processing Load Collectors.
Info:     Processing Equations.
Info:     Processing Loads.
Info:     Processing Assemblies.
Info:     Processing Curves.
Info:     Processing Blocks.
Info:     Processing Sets.
Info:     Processing Output Blocks.
Info:     Processing Load Steps.
Info:     Processing Sensors.
Info:     Processing Plys.
Info:     Processing Laminates.
Info:     Processing Designvars.
Info:     Processing Beamsectcols.
Info:     Processing Beamsections.
Info:     Processing Optitableentrs.
Info:     Processing Dequations.
Info:     Processing Optiresponses.
Info:     Processing Dvprels.
Info:     Processing Opticonstraints.
Info:     Processing Desvarlinks.
Info:     Processing Objectives.
Info:     Processing Opticontrols.
Info:     Processing Optidscreens.
Info:     Processing Tags.
Info:     Processing Dobjrefs.
Info:     Processing Contactsurfs.
Info:     Processing Shapes.
Info:     Processing Ddvals.
Info:     Processing Joints.
Info:     Processing Mechanismconstraints.
Info:     Processing Rigidwalls.
Info:     Processing Failures.
Info:     Processing Crosssections.
Info:     Processing Hourglass.
Info:     Processing Rigidbodies.
Info:     Processing Bodies.
Info:     Processing Mechanisms.
Info:     Processing Transformations.
Info:     Processing Positions.
Info:     Processing Outputrequests.
Info:     Processing Directmatrixinputs.
Info:     Processing Equivalences.
Info:     Processing Solvermasses.
Info:     Processing Analysisparameters.
Info:     Processing Parameters.

Summary:  Feinput finished with 0 errors and 0 warnings.
Info:     Translation Complete.
Info:     Reading OPTISTRUCT from C:/Users/sihol/OneDrive/Desktop/ASE/MATLAB/RESULT FILES/ASE_Project2025_SuperPanel_3787415_redesign.fem using C:\Program Files\Altair\2023.1\hwdesktop\io\model_readers\feinput\bin\win64\optistruct.exe on 07-06-2025 20:57:56.
Info:     Processing Modules.
Info:     Processing Cards.
Info:     Processing System Collectors.
Info:     Processing Systems.
Info:     Processing Nodes.
Info:     Processing Vectorcols.
Info:     Processing Vectors.
Info:     Processing Materials.
Info:     Processing Properties.
Info:     Processing Components.
Info:     Processing Groups.
Info:     Processing Elements.
Info:     Processing Load Collectors.
Info:     Processing Equations.
Info:     Processing Loads.
Info:     Processing Assemblies.
Info:     Processing Curves.
Info:     Processing Blocks.
Info:     Processing Sets.
Info:     Processing Output Blocks.
Info:     Processing Load Steps.
Info:     Processing Sensors.
Info:     Processing Plys.
Info:     Processing Laminates.
Info:     Processing Designvars.
Info:     Processing Beamsectcols.
Info:     Processing Beamsections.
Info:     Processing Optitableentrs.
Info:     Processing Dequations.
Info:     Processing Optiresponses.
Info:     Processing Dvprels.
Info:     Processing Opticonstraints.
Info:     Processing Desvarlinks.
Info:     Processing Objectives.
Info:     Processing Opticontrols.
Info:     Processing Optidscreens.
Info:     Processing Tags.
Info:     Processing Dobjrefs.
Info:     Processing Contactsurfs.
Info:     Processing Shapes.
Info:     Processing Ddvals.
Info:     Processing Joints.
Info:     Processing Mechanismconstraints.
Info:     Processing Rigidwalls.
Info:     Processing Failures.
Info:     Processing Crosssections.
Info:     Processing Hourglass.
Info:     Processing Rigidbodies.
Info:     Processing Bodies.
Info:     Processing Mechanisms.
Info:     Processing Transformations.
Info:     Processing Positions.
Info:     Processing Outputrequests.
Info:     Processing Directmatrixinputs.
Info:     Processing Equivalences.
Info:     Processing Solvermasses.
Info:     Processing Analysisparameters.
Info:     Processing Parameters.

Summary:  Feinput finished with 0 errors and 0 warnings.
Info:     Translation Complete.
Info:     Reading OPTISTRUCT from C:/Users/sihol/OneDrive/Desktop/ASE/MATLAB/RESULT FILES/ASE_Project2025_SuperPanel_3787415_redesign.fem using C:\Program Files\Altair\2023.1\hwdesktop\io\model_readers\feinput\bin\win64\optistruct.exe on 07-06-2025 21:00:46.
Info:     Processing Modules.
Info:     Processing Cards.
Info:     Processing System Collectors.
Info:     Processing Systems.
Info:     Processing Nodes.
Info:     Processing Vectorcols.
Info:     Processing Vectors.
Info:     Processing Materials.
Info:     Processing Properties.
Info:     Processing Components.
Info:     Processing Groups.
Info:     Processing Elements.
Info:     Processing Load Collectors.
Info:     Processing Equations.
Info:     Processing Loads.
Info:     Processing Assemblies.
Info:     Processing Curves.
Info:     Processing Blocks.
Info:     Processing Sets.
Info:     Processing Output Blocks.
Info:     Processing Load Steps.
Info:     Processing Sensors.
Info:     Processing Plys.
Info:     Processing Laminates.
Info:     Processing Designvars.
Info:     Processing Beamsectcols.
Info:     Processing Beamsections.
Info:     Processing Optitableentrs.
Info:     Processing Dequations.
Info:     Processing Optiresponses.
Info:     Processing Dvprels.
Info:     Processing Opticonstraints.
Info:     Processing Desvarlinks.
Info:     Processing Objectives.
Info:     Processing Opticontrols.
Info:     Processing Optidscreens.
Info:     Processing Tags.
Info:     Processing Dobjrefs.
Info:     Processing Contactsurfs.
Info:     Processing Shapes.
Info:     Processing Ddvals.
Info:     Processing Joints.
Info:     Processing Mechanismconstraints.
Info:     Processing Rigidwalls.
Info:     Processing Failures.
Info:     Processing Crosssections.
Info:     Processing Hourglass.
Info:     Processing Rigidbodies.
Info:     Processing Bodies.
Info:     Processing Mechanisms.
Info:     Processing Transformations.
Info:     Processing Positions.
Info:     Processing Outputrequests.
Info:     Processing Directmatrixinputs.
Info:     Processing Equivalences.
Info:     Processing Solvermasses.
Info:     Processing Analysisparameters.
Info:     Processing Parameters.

Summary:  Feinput finished with 0 errors and 0 warnings.
Info:     Translation Complete.
Info:     Reading OPTISTRUCT from C:/Users/sihol/OneDrive/Desktop/ASE/MATLAB/RESULT FILES/ASE_Project2025_SuperPanel_3787415_redesign.fem using C:\Program Files\Altair\2023.1\hwdesktop\io\model_readers\feinput\bin\win64\optistruct.exe on 07-06-2025 21:02:00.
Info:     Processing Modules.
Info:     Processing Cards.
Info:     Processing System Collectors.
Info:     Processing Systems.
Info:     Processing Nodes.
Info:     Processing Vectorcols.
Info:     Processing Vectors.
Info:     Processing Materials.
Info:     Processing Properties.
Info:     Processing Components.
Info:     Processing Groups.
Info:     Processing Elements.
Info:     Processing Load Collectors.
Info:     Processing Equations.
Info:     Processing Loads.
Info:     Processing Assemblies.
Info:     Processing Curves.
Info:     Processing Blocks.
Info:     Processing Sets.
Info:     Processing Output Blocks.
Info:     Processing Load Steps.
Info:     Processing Sensors.
Info:     Processing Plys.
Info:     Processing Laminates.
Info:     Processing Designvars.
Info:     Processing Beamsectcols.
Info:     Processing Beamsections.
Info:     Processing Optitableentrs.
Info:     Processing Dequations.
Info:     Processing Optiresponses.
Info:     Processing Dvprels.
Info:     Processing Opticonstraints.
Info:     Processing Desvarlinks.
Info:     Processing Objectives.
Info:     Processing Opticontrols.
Info:     Processing Optidscreens.
Info:     Processing Tags.
Info:     Processing Dobjrefs.
Info:     Processing Contactsurfs.
Info:     Processing Shapes.
Info:     Processing Ddvals.
Info:     Processing Joints.
Info:     Processing Mechanismconstraints.
Info:     Processing Rigidwalls.
Info:     Processing Failures.
Info:     Processing Crosssections.
Info:     Processing Hourglass.
Info:     Processing Rigidbodies.
Info:     Processing Bodies.
Info:     Processing Mechanisms.
Info:     Processing Transformations.
Info:     Processing Positions.
Info:     Processing Outputrequests.
Info:     Processing Directmatrixinputs.
Info:     Processing Equivalences.
Info:     Processing Solvermasses.
Info:     Processing Analysisparameters.
Info:     Processing Parameters.

Summary:  Feinput finished with 0 errors and 0 warnings.
Info:     Translation Complete.
